import { User, ApiItem, ApiCategory } from "@/types";

const avatarBase = "https://api.dicebear.com/7.x/avataaars/svg?seed=";

const apiUsers: User[] = [
    { id: "au1", name: "Ravi Patel", email: "ravi@example.com", image: `${avatarBase}ravi`, role: "SELLER", bio: "API architect & backend engineer. 12+ yrs building scalable APIs.", createdAt: "2024-01-10" },
    { id: "au2", name: "Nina Torres", email: "nina@example.com", image: `${avatarBase}nina`, role: "SELLER", bio: "Data & ML engineer turning models into production APIs.", createdAt: "2024-02-05" },
    { id: "au3", name: "Jackson Lee", email: "jacks@example.com", image: `${avatarBase}jacks`, role: "SELLER", bio: "Fintech backend developer. Payments & fraud detection expert.", createdAt: "2024-03-20" },
    { id: "au4", name: "Priya Sharma", email: "priya@example.com", image: `${avatarBase}priya`, role: "SELLER", bio: "NLP researcher shipping language AI via REST APIs.", createdAt: "2024-01-28" },
    { id: "au5", name: "Omar Hassan", email: "omar@example.com", image: `${avatarBase}omar`, role: "SELLER", bio: "Cloud infra engineer. Auth, storage, and infra APIs.", createdAt: "2024-04-12" },
];

export const apiCategories: ApiCategory[] = [
    { id: "ac1", name: "AI & Machine Learning", slug: "ai-ml", icon: "🤖", description: "LLMs, vision, NLP, and generative AI APIs", apiCount: 6 },
    { id: "ac2", name: "Payments & Finance", slug: "payments", icon: "💳", description: "Payments, invoicing, and banking APIs", apiCount: 4 },
    { id: "ac3", name: "Communication", slug: "communication", icon: "📨", description: "Email, SMS, push, and voice APIs", apiCount: 3 },
    { id: "ac4", name: "Authentication", slug: "auth", icon: "🔐", description: "OAuth, JWT, SSO, and identity APIs", apiCount: 2 },
    { id: "ac5", name: "Data & Analytics", slug: "data-analytics", icon: "📊", description: "Data enrichment, analytics, and insights APIs", apiCount: 3 },
    { id: "ac6", name: "Maps & Location", slug: "maps-location", icon: "🗺️", description: "Geocoding, routing, and location intelligence", apiCount: 2 },
];

const apiTagPool = [
    { id: "at1", name: "REST" }, { id: "at2", name: "GraphQL" },
    { id: "at3", name: "TypeScript SDK" }, { id: "at4", name: "Webhooks" },
    { id: "at5", name: "Streaming" }, { id: "at6", name: "Real-time" },
    { id: "at7", name: "OpenAPI" }, { id: "at8", name: "Node.js" },
    { id: "at9", name: "Python" }, { id: "at10", name: "High-Latency" },
];
const at = (idxs: number[]) => idxs.map(i => apiTagPool[i]);

export const apis: ApiItem[] = [
    // ── AI & ML ───────────────────────────────────────────────────────────────
    {
        id: "api1", name: "NeuralText AI", slug: "neuraltext-ai",
        description: "A production-grade LLM API for text generation, summarization, translation, and Q&A — powered by a fine-tuned GPT-4-class model.",
        longDescription: "NeuralText AI exposes a chat-completion endpoint plus streaming support. Fine-tune on your own data, use our built-in prompt templates, and leverage structured JSON output mode. Supports 40+ languages, 128k context window, and comes with a TypeScript & Python SDK.",
        baseUrl: "https://api.neuraltext.ai/v1",
        version: "1.4.0", category: apiCategories[0], categoryId: "ac1",
        tags: at([0, 2, 4, 6, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 29, teamPrice: 79, enterprisePrice: 299,
        freeCallsPerMonth: 500,
        endpoints: [
            { method: "POST", path: "/chat/completions", description: "Generate text with a chat model" },
            { method: "POST", path: "/completions", description: "Raw completion endpoint" },
            { method: "POST", path: "/embeddings", description: "Generate vector embeddings" },
            { method: "GET", path: "/models", description: "List available models" },
        ],
        documentation: "Initialize with your API key, POST to /chat/completions with a messages array.",
        codeSnippet: `import { NeuralText } from '@getapi/neuraltext';\n\nconst client = new NeuralText({ apiKey: process.env.NEURALTEXT_KEY });\n\nconst res = await client.chat.completions.create({\n  model: 'nt-4-turbo',\n  messages: [{ role: 'user', content: 'Summarize this text...' }],\n  stream: true,\n});\n\nfor await (const chunk of res) console.log(chunk.delta.content);`,
        status: "PUBLISHED", featured: true,
        callCount: 8_420_000, averageRating: 4.9, reviewCount: 312,
        uptime: 99.98, latencyMs: 180,
        creator: apiUsers[3], creatorId: "au4", createdAt: "2024-03-01", updatedAt: "2024-12-15",
    },
    {
        id: "api2", name: "VisionAI Object Detection", slug: "visionai-object-detection",
        description: "Detect objects, faces, text, barcodes, and scenes in images and video streams with sub-100ms latency.",
        longDescription: "VisionAI uses a custom YOLO-v9-based architecture fine-tuned on 80 COCO classes plus 30 additional custom ones. Supports JPEG, PNG, WebP, and MP4. Includes confidence scores, bounding boxes, and segmentation masks. Available as both REST and WebSocket streaming.",
        baseUrl: "https://api.visionai.dev/v2",
        version: "2.1.0", category: apiCategories[0], categoryId: "ac1",
        tags: at([0, 4, 5, 6, 8]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 5, teamPrice: 15, enterprisePrice: 49,
        freeCallsPerMonth: 1000,
        endpoints: [
            { method: "POST", path: "/detect", description: "Detect objects in an image URL or base64" },
            { method: "POST", path: "/ocr", description: "Extract text from images" },
            { method: "POST", path: "/faces", description: "Detect and analyze faces" },
            { method: "POST", path: "/classify", description: "Classify image into top-5 categories" },
        ],
        documentation: "Send a POST with image_url or base64_image. Returns an array of detections with box coords.",
        codeSnippet: `const res = await fetch('https://api.visionai.dev/v2/detect', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.VISION_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ image_url: 'https://example.com/photo.jpg', confidence: 0.7 }),\n});\nconst { detections } = await res.json();\nconsole.log(detections); // [{ label, confidence, box }]`,
        status: "PUBLISHED", featured: true,
        callCount: 5_100_000, averageRating: 4.8, reviewCount: 201,
        uptime: 99.95, latencyMs: 85,
        creator: apiUsers[1], creatorId: "au2", createdAt: "2024-04-10", updatedAt: "2024-12-01",
    },
    {
        id: "api3", name: "SentimentPulse NLP", slug: "sentimentpulse-nlp",
        description: "Analyze sentiment, emotion, intent, and named entities from text in 30+ languages.",
        longDescription: "SentimentPulse is a multilingual NLP pipeline that returns sentiment (positive/negative/neutral with score), emotion classification (joy, anger, fear, sadness, surprise), named entity recognition (PER, ORG, LOC, DATE), and intent detection for customer support automation.",
        baseUrl: "https://api.sentimentpulse.io/v1",
        version: "1.2.0", category: apiCategories[0], categoryId: "ac1",
        tags: at([0, 2, 6, 7, 8]),
        authType: "BEARER", pricingModel: "FREEMIUM",
        price: 19, teamPrice: 59, enterprisePrice: 199,
        freeCallsPerMonth: 2000,
        endpoints: [
            { method: "POST", path: "/analyze", description: "Full NLP analysis pipeline" },
            { method: "POST", path: "/sentiment", description: "Sentiment score only" },
            { method: "POST", path: "/entities", description: "Named entity recognition" },
            { method: "POST", path: "/intent", description: "User intent classification" },
        ],
        documentation: "POST plain text or an array of texts. Returns structured JSON with scores and labels.",
        codeSnippet: `const res = await fetch('https://api.sentimentpulse.io/v1/analyze', {\n  method: 'POST',\n  headers: { Authorization: \`Bearer \${process.env.SP_KEY}\`, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ text: 'The product is amazing but shipping was slow.', lang: 'en' }),\n});\nconst data = await res.json();\n// { sentiment: 'mixed', score: 0.62, emotions: { joy: 0.7, anger: 0.3 } }`,
        status: "PUBLISHED", featured: false,
        callCount: 3_200_000, averageRating: 4.7, reviewCount: 143,
        uptime: 99.9, latencyMs: 120,
        creator: apiUsers[3], creatorId: "au4", createdAt: "2024-05-01", updatedAt: "2024-11-20",
    },
    {
        id: "api4", name: "CodeGen Copilot API", slug: "codegen-copilot-api",
        description: "AI-powered code generation, completion, explanation, and bug-fixing for 40+ programming languages.",
        longDescription: "CodeGen Copilot is built on a 34B parameter code-specialized model. Generate functions from docstrings, complete partial snippets, explain obfuscated code, detect vulnerabilities, and auto-fix bugs. Supports streaming output and integrates with VS Code via our extension.",
        baseUrl: "https://api.codegenai.dev/v1",
        version: "3.0.0", category: apiCategories[0], categoryId: "ac1",
        tags: at([0, 2, 4, 6, 7]),
        authType: "API_KEY", pricingModel: "SUBSCRIPTION",
        price: 49, teamPrice: 129, enterprisePrice: 499,
        freeCallsPerMonth: 200,
        endpoints: [
            { method: "POST", path: "/generate", description: "Generate code from a prompt or docstring" },
            { method: "POST", path: "/complete", description: "Complete a partial code snippet" },
            { method: "POST", path: "/explain", description: "Explain what a code block does" },
            { method: "POST", path: "/fix", description: "Detect and fix bugs in code" },
        ],
        documentation: "Supply a prompt and language. Optionally pass existing code as context for completion.",
        codeSnippet: `import { CodeGen } from '@getapi/codegen';\n\nconst cg = new CodeGen({ apiKey: process.env.CODEGEN_KEY });\n\nconst { code } = await cg.generate({\n  prompt: 'A function that debounces async calls in TypeScript',\n  language: 'typescript',\n  stream: false,\n});\nconsole.log(code);`,
        status: "PUBLISHED", featured: true,
        callCount: 6_700_000, averageRating: 4.9, reviewCount: 380,
        uptime: 99.97, latencyMs: 220,
        creator: apiUsers[0], creatorId: "au1", createdAt: "2024-02-15", updatedAt: "2024-12-10",
    },
    {
        id: "api5", name: "ImageForge AI", slug: "imageforge-ai",
        description: "Generate, edit, upscale, and stylize images using diffusion models with a simple REST API.",
        longDescription: "ImageForge supports text-to-image (SDXL, Flux), image-to-image, inpainting, outpainting, and style transfer. Output is returned as URLs or base64. Choose from prebuilt styles (photorealistic, anime, sketch, watercolor) or supply custom LoRA weights.",
        baseUrl: "https://api.imageforge.ai/v1",
        version: "2.0.0", category: apiCategories[0], categoryId: "ac1",
        tags: at([0, 2, 5, 6, 7]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 10, teamPrice: 29, enterprisePrice: 99,
        freeCallsPerMonth: 50,
        endpoints: [
            { method: "POST", path: "/generate", description: "Text-to-image generation" },
            { method: "POST", path: "/edit", description: "Edit image regions with a mask and prompt" },
            { method: "POST", path: "/upscale", description: "Upscale image 2× or 4× with AI" },
            { method: "POST", path: "/stylize", description: "Apply art style transfer to an image" },
        ],
        documentation: "POST a prompt with size and style params. Returns a signed URL to the generated image.",
        codeSnippet: `const res = await fetch('https://api.imageforge.ai/v1/generate', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.FORGE_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ prompt: 'A futuristic city at dusk, cinematic', width: 1024, height: 1024 }),\n});\nconst { url } = await res.json();\nconsole.log(url); // https://cdn.imageforge.ai/...`,
        status: "PUBLISHED", featured: true,
        callCount: 12_000_000, averageRating: 4.8, reviewCount: 275,
        uptime: 99.9, latencyMs: 3200,
        creator: apiUsers[1], creatorId: "au2", createdAt: "2024-03-20", updatedAt: "2024-12-08",
    },
    {
        id: "api6", name: "TranscribeAI Speech", slug: "transcribeai-speech",
        description: "Convert audio and video to text with speaker diarization, timestamps, and 95%+ accuracy across 50 languages.",
        longDescription: "TranscribeAI is built on a Whisper-large-v3 fine-tuned ensemble. Supports MP3, WAV, M4A, FLAC, and MP4 up to 2GB. Real-time streaming transcription via WebSocket, batch processing via REST. Returns word-level timestamps, speaker labels, punctuation, and confidence scores.",
        baseUrl: "https://api.transcribeai.io/v2",
        version: "2.3.0", category: apiCategories[0], categoryId: "ac1",
        tags: at([0, 4, 5, 6, 8]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 5, teamPrice: 12, enterprisePrice: 39,
        freeCallsPerMonth: 300,
        endpoints: [
            { method: "POST", path: "/transcribe", description: "Transcribe an audio file URL" },
            { method: "POST", path: "/diarize", description: "Transcribe with speaker labels" },
            { method: "GET", path: "/jobs/:id", description: "Poll async transcription job status" },
            { method: "WS", path: "/stream", description: "Real-time streaming transcription" } as any,
        ],
        documentation: "POST audio_url and language. Returns transcript text with word-level timestamps.",
        codeSnippet: `const res = await fetch('https://api.transcribeai.io/v2/transcribe', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.TRANSCRIBE_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ audio_url: 'https://example.com/meeting.mp3', language: 'en', diarize: true }),\n});\nconst { transcript, speakers } = await res.json();`,
        status: "PUBLISHED", featured: false,
        callCount: 4_500_000, averageRating: 4.7, reviewCount: 189,
        uptime: 99.92, latencyMs: 1800,
        creator: apiUsers[3], creatorId: "au4", createdAt: "2024-05-15", updatedAt: "2024-11-28",
    },

    // ── Payments & Finance ───────────────────────────────────────────────────
    {
        id: "api7", name: "PayFlow Payments API", slug: "payflow-payments",
        description: "Accept credit cards, bank transfers, and 50+ payment methods globally with a single integration.",
        longDescription: "PayFlow handles charge creation, subscription billing, refunds, disputes, and webhooks. Supports 130+ currencies, 3D Secure 2.0, SCA compliance, and real-time fraud scoring. Comes with pre-built checkout UI (React component) and a full TypeScript SDK.",
        baseUrl: "https://api.payflow.io/v1",
        version: "4.1.0", category: apiCategories[1], categoryId: "ac2",
        tags: at([0, 2, 3, 6, 7]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 0, teamPrice: 0, enterprisePrice: 99,
        freeCallsPerMonth: -1, // pricing is % per transaction
        endpoints: [
            { method: "POST", path: "/charges", description: "Create a charge" },
            { method: "POST", path: "/refunds", description: "Refund a charge" },
            { method: "POST", path: "/subscriptions", description: "Create a recurring subscription" },
            { method: "GET", path: "/charges/:id", description: "Retrieve charge details" },
            { method: "POST", path: "/webhooks", description: "Register a webhook endpoint" },
        ],
        documentation: "Supply a payment_method_id from our client SDK and an amount in cents.",
        codeSnippet: `import PayFlow from '@getapi/payflow';\n\nconst pf = new PayFlow({ secretKey: process.env.PF_SECRET });\n\nconst charge = await pf.charges.create({\n  amount: 4999,        // $49.99\n  currency: 'usd',\n  payment_method: 'pm_xxxx',\n  confirm: true,\n});\nconsole.log(charge.status); // 'succeeded'`,
        status: "PUBLISHED", featured: true,
        callCount: 22_000_000, averageRating: 4.9, reviewCount: 456,
        uptime: 99.99, latencyMs: 95,
        creator: apiUsers[2], creatorId: "au3", createdAt: "2024-01-20", updatedAt: "2024-12-20",
    },
    {
        id: "api8", name: "CryptoRates Ticker API", slug: "cryptorates-ticker",
        description: "Real-time and historical price data for 10,000+ crypto assets across 100+ exchanges.",
        longDescription: "CryptoRates aggregates OHLCV data, order book depth, trade feeds, and portfolio analytics. WebSocket subscriptions deliver sub-100ms price updates. REST endpoints support historical candles from 2010 onwards, market cap rankings, and DEX liquidity data.",
        baseUrl: "https://api.cryptorates.io/v3",
        version: "3.0.0", category: apiCategories[1], categoryId: "ac2",
        tags: at([0, 1, 5, 6, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 49, teamPrice: 149, enterprisePrice: 499,
        freeCallsPerMonth: 10000,
        endpoints: [
            { method: "GET", path: "/prices", description: "Get current prices for multiple coins" },
            { method: "GET", path: "/candles/:pair", description: "OHLCV historical candles" },
            { method: "GET", path: "/orderbook/:pair", description: "Live order book depth" },
            { method: "WS", path: "/ticker", description: "Real-time price feed" } as any,
        ],
        documentation: "Pass coin IDs as a comma-separated list to /prices. Currency defaults to USD.",
        codeSnippet: `const res = await fetch(\n  'https://api.cryptorates.io/v3/prices?ids=bitcoin,ethereum,solana&currency=usd',\n  { headers: { 'X-API-Key': process.env.CR_KEY } }\n);\nconst prices = await res.json();\n// { bitcoin: { usd: 68420 }, ethereum: { usd: 3210 } }`,
        status: "PUBLISHED", featured: false,
        callCount: 9_800_000, averageRating: 4.7, reviewCount: 178,
        uptime: 99.95, latencyMs: 45,
        creator: apiUsers[2], creatorId: "au3", createdAt: "2024-04-01", updatedAt: "2024-12-01",
    },
    {
        id: "api9", name: "InvoiceBot API", slug: "invoicebot-api",
        description: "Generate, send, and track professional PDF invoices programmatically with payment link integration.",
        longDescription: "InvoiceBot turns JSON data into beautifully styled PDF invoices in 200ms. Supports multi-currency, tax calculation (VAT, GST, US sales tax), custom branding, e-signature, and automatic payment reminders. Integrates with PayFlow and Stripe for one-click payment collection.",
        baseUrl: "https://api.invoicebot.io/v1",
        version: "1.5.0", category: apiCategories[1], categoryId: "ac2",
        tags: at([0, 2, 3, 6, 7]),
        authType: "BEARER", pricingModel: "SUBSCRIPTION",
        price: 29, teamPrice: 69, enterprisePrice: 199,
        freeCallsPerMonth: 50,
        endpoints: [
            { method: "POST", path: "/invoices", description: "Create and generate a PDF invoice" },
            { method: "POST", path: "/invoices/:id/send", description: "Email invoice to customer" },
            { method: "GET", path: "/invoices/:id", description: "Get invoice status and PDF URL" },
            { method: "POST", path: "/invoices/:id/remind", description: "Send a payment reminder" },
        ],
        documentation: "POST invoice data with line items. Returns a PDF URL and shareable payment link.",
        codeSnippet: `const res = await fetch('https://api.invoicebot.io/v1/invoices', {\n  method: 'POST',\n  headers: { Authorization: \`Bearer \${process.env.IB_KEY}\`, 'Content-Type': 'application/json' },\n  body: JSON.stringify({\n    customer: { name: 'Acme Corp', email: 'pay@acme.com' },\n    items: [{ description: 'UI Component License', qty: 1, unit_price: 199 }],\n    currency: 'USD',\n  }),\n});\nconst { pdf_url, payment_link } = await res.json();`,
        status: "PUBLISHED", featured: false,
        callCount: 1_200_000, averageRating: 4.6, reviewCount: 92,
        uptime: 99.9, latencyMs: 210,
        creator: apiUsers[2], creatorId: "au3", createdAt: "2024-06-10", updatedAt: "2024-11-15",
    },
    {
        id: "api10", name: "FraudShield Detection API", slug: "fraudshield-detection",
        description: "Real-time fraud scoring for transactions, logins, and signups using multi-model ML and behavioral analysis.",
        longDescription: "FraudShield analyzes 200+ signals per request — velocity checks, device fingerprinting, IP reputation, card BIN lookup, and behavioral biometrics — in under 80ms. Returns a 0–100 risk score with a recommendation (allow/review/block) and detailed reason codes.",
        baseUrl: "https://api.fraudshield.io/v2",
        version: "2.2.0", category: apiCategories[1], categoryId: "ac2",
        tags: at([0, 2, 3, 6, 7]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 2, teamPrice: 5, enterprisePrice: 15,
        freeCallsPerMonth: 1000,
        endpoints: [
            { method: "POST", path: "/score/transaction", description: "Score a payment transaction" },
            { method: "POST", path: "/score/login", description: "Score a login attempt" },
            { method: "POST", path: "/score/signup", description: "Score a new account registration" },
            { method: "GET", path: "/rules", description: "List active fraud rules" },
        ],
        documentation: "POST transaction or event data. Response includes score, recommendation, and risk factors.",
        codeSnippet: `const res = await fetch('https://api.fraudshield.io/v2/score/transaction', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.FS_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ amount: 9900, currency: 'usd', ip: '1.2.3.4', card_bin: '411111' }),\n});\nconst { score, recommendation } = await res.json();\n// score: 12, recommendation: 'allow'`,
        status: "PUBLISHED", featured: false,
        callCount: 18_000_000, averageRating: 4.8, reviewCount: 234,
        uptime: 99.99, latencyMs: 72,
        creator: apiUsers[2], creatorId: "au3", createdAt: "2024-02-01", updatedAt: "2024-12-18",
    },

    // ── Communication ────────────────────────────────────────────────────────
    {
        id: "api11", name: "MessengerGrid Email API", slug: "messengergrid-email",
        description: "Send transactional and marketing emails at scale with analytics, templates, and deliverability optimization.",
        longDescription: "MessengerGrid provides SMTP relay, REST API, and drag-and-drop template editor. Features include: real-time event webhooks (open, click, bounce), IP warming, suppression lists, DKIM/SPF auto-config, A/B testing, and detailed deliverability reports. 99.5% deliverability rate guaranteed.",
        baseUrl: "https://api.messengergrid.com/v1",
        version: "1.9.0", category: apiCategories[2], categoryId: "ac3",
        tags: at([0, 2, 3, 6, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 19, teamPrice: 59, enterprisePrice: 249,
        freeCallsPerMonth: 300,
        endpoints: [
            { method: "POST", path: "/mail/send", description: "Send a single or batch email" },
            { method: "POST", path: "/templates", description: "Create a reusable email template" },
            { method: "GET", path: "/stats/email/:id", description: "Get delivery stats for a sent email" },
            { method: "POST", path: "/webhooks", description: "Register email event webhooks" },
        ],
        documentation: "POST to /mail/send with to, subject, and html or template_id.",
        codeSnippet: `import { MessengerGrid } from '@getapi/messengergrid';\n\nconst mg = new MessengerGrid({ apiKey: process.env.MG_KEY });\n\nawait mg.mail.send({\n  from: 'noreply@myapp.com',\n  to: ['user@example.com'],\n  subject: 'Welcome to Get API! 🎉',\n  template_id: 'welcome-v2',\n  variables: { name: 'Alex', plan: 'Team' },\n});`,
        status: "PUBLISHED", featured: true,
        callCount: 7_500_000, averageRating: 4.8, reviewCount: 267,
        uptime: 99.95, latencyMs: 140,
        creator: apiUsers[4], creatorId: "au5", createdAt: "2024-03-10", updatedAt: "2024-12-05",
    },
    {
        id: "api12", name: "PingText SMS Gateway", slug: "pingtext-sms-gateway",
        description: "Send OTP, alerts, and marketing SMS to 200+ countries with delivery receipts and two-way messaging.",
        longDescription: "PingText routes SMS through redundant carrier networks ensuring 96%+ delivery in under 3 seconds. Features: OTP templates with auto-expiry, number lookup (carrier + validity), two-way messaging (receive inbound SMS via webhook), and compliance tools for GDPR & TCPA.",
        baseUrl: "https://api.pingtext.io/v1",
        version: "1.3.0", category: apiCategories[2], categoryId: "ac3",
        tags: at([0, 2, 3, 6, 7]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 1, teamPrice: 3, enterprisePrice: 8,
        freeCallsPerMonth: 50,
        endpoints: [
            { method: "POST", path: "/sms/send", description: "Send an SMS to one or multiple numbers" },
            { method: "POST", path: "/sms/otp", description: "Send and verify OTP in one call" },
            { method: "GET", path: "/sms/:id", description: "Get delivery status of a sent SMS" },
            { method: "POST", path: "/numbers/lookup", description: "Validate and get carrier info for a number" },
        ],
        documentation: "POST to /sms/send with to (E.164 format), from, and body.",
        codeSnippet: `const res = await fetch('https://api.pingtext.io/v1/sms/send', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.PT_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ to: '+14155551234', from: '+18005550001', body: 'Your OTP is 482910' }),\n});\nconst { message_id, status } = await res.json();`,
        status: "PUBLISHED", featured: false,
        callCount: 14_200_000, averageRating: 4.7, reviewCount: 198,
        uptime: 99.97, latencyMs: 320,
        creator: apiUsers[4], creatorId: "au5", createdAt: "2024-04-20", updatedAt: "2024-11-25",
    },
    {
        id: "api13", name: "PushWave Push Notifications", slug: "pushwave-push-notifications",
        description: "Send web push, iOS, and Android push notifications to millions of devices in parallel with <200ms latency.",
        longDescription: "PushWave abstracts APNs, FCM, and Web Push into a single API. Features: personalized payloads with variables, scheduled delivery, A/B testing, segmentation by user attributes, and detailed analytics (delivered, opened, dismissed rates). SDKs for React Native, Flutter, and Web.",
        baseUrl: "https://api.pushwave.io/v2",
        version: "2.0.0", category: apiCategories[2], categoryId: "ac3",
        tags: at([0, 2, 3, 5, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 29, teamPrice: 89, enterprisePrice: 299,
        freeCallsPerMonth: 10000,
        endpoints: [
            { method: "POST", path: "/notifications/send", description: "Send to one or many device tokens" },
            { method: "POST", path: "/notifications/broadcast", description: "Broadcast to a segment or topic" },
            { method: "POST", path: "/notifications/schedule", description: "Schedule a notification for later" },
            { method: "GET", path: "/notifications/:id/stats", description: "Get delivery analytics" },
        ],
        documentation: "POST tokens array, title, body, and optional data payload to /notifications/send.",
        codeSnippet: `const res = await fetch('https://api.pushwave.io/v2/notifications/send', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.PW_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({\n    tokens: ['device_token_here'],\n    title: 'New component released!',\n    body: 'Check out the Aurora Hero Section',\n    data: { url: '/components/aurora-hero-section' },\n  }),\n});`,
        status: "PUBLISHED", featured: false,
        callCount: 55_000_000, averageRating: 4.6, reviewCount: 143,
        uptime: 99.95, latencyMs: 180,
        creator: apiUsers[4], creatorId: "au5", createdAt: "2024-05-01", updatedAt: "2024-12-10",
    },

    // ── Authentication ───────────────────────────────────────────────────────
    {
        id: "api14", name: "AuthVault Identity API", slug: "authvault-identity",
        description: "Turnkey authentication: magic links, OTP, OAuth, MFA, and session management in one API.",
        longDescription: "AuthVault replaces your entire auth stack. Sign users in with email magic link, SMS OTP, Google/GitHub/Apple OAuth, or passkeys. Manage sessions with JWT + refresh tokens, enforce MFA policies, detect suspicious logins, and block credential stuffing attacks.",
        baseUrl: "https://api.authvault.dev/v1",
        version: "1.6.0", category: apiCategories[3], categoryId: "ac4",
        tags: at([0, 2, 3, 6, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 25, teamPrice: 75, enterprisePrice: 299,
        freeCallsPerMonth: 5000,
        endpoints: [
            { method: "POST", path: "/auth/magic-link", description: "Send a magic link to email" },
            { method: "POST", path: "/auth/otp/send", description: "Send SMS OTP" },
            { method: "POST", path: "/auth/otp/verify", description: "Verify OTP and issue tokens" },
            { method: "POST", path: "/auth/token/refresh", description: "Refresh access token" },
            { method: "GET", path: "/session", description: "Validate and return current session" },
        ],
        documentation: "Initialize with your project ID and secret. Use the client SDK for browser-side flows.",
        codeSnippet: `import { AuthVault } from '@getapi/authvault';\n\nconst av = new AuthVault({ projectId: 'proj_xxx', secret: process.env.AV_SECRET });\n\n// Send magic link\nawait av.auth.sendMagicLink({ email: 'user@example.com', redirectUrl: '/dashboard' });\n\n// Server-side session validation\nconst session = await av.session.verify(req.cookies['av_session']);\nconsole.log(session.userId);`,
        status: "PUBLISHED", featured: true,
        callCount: 3_900_000, averageRating: 4.9, reviewCount: 211,
        uptime: 99.99, latencyMs: 88,
        creator: apiUsers[4], creatorId: "au5", createdAt: "2024-03-05", updatedAt: "2024-12-15",
    },
    {
        id: "api15", name: "PermitLayer RBAC API", slug: "permitlayer-rbac",
        description: "Fine-grained authorization with roles, permissions, policies, and audit logs — all as a service.",
        longDescription: "PermitLayer implements RBAC, ABAC, and ReBAC authorization models via a simple check() call. Define roles and permissions in the dashboard or via API, sync with your existing user system, and enforce policy at the edge. Includes real-time audit logs and a permission debugger.",
        baseUrl: "https://api.permitlayer.io/v1",
        version: "1.1.0", category: apiCategories[3], categoryId: "ac4",
        tags: at([0, 2, 3, 6, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 29, teamPrice: 89, enterprisePrice: 349,
        freeCallsPerMonth: 50000,
        endpoints: [
            { method: "POST", path: "/check", description: "Check if a user has a permission" },
            { method: "POST", path: "/roles/:id/assign", description: "Assign a role to a user" },
            { method: "GET", path: "/roles", description: "List all roles" },
            { method: "GET", path: "/audit", description: "Query permission audit logs" },
        ],
        documentation: "Call /check with user, action, and resource. Returns allowed: true/false in <10ms.",
        codeSnippet: `import { PermitLayer } from '@getapi/permitlayer';\n\nconst pl = new PermitLayer({ apiKey: process.env.PL_KEY });\n\nconst allowed = await pl.check({\n  user: 'user_123',\n  action: 'delete',\n  resource: { type: 'invoice', id: 'inv_456', tenant: 'acme' },\n});\n\nif (!allowed) throw new Error('Forbidden');`,
        status: "PUBLISHED", featured: false,
        callCount: 2_100_000, averageRating: 4.7, reviewCount: 98,
        uptime: 99.95, latencyMs: 9,
        creator: apiUsers[4], creatorId: "au5", createdAt: "2024-06-01", updatedAt: "2024-11-30",
    },

    // ── Data & Analytics ─────────────────────────────────────────────────────
    {
        id: "api16", name: "DataEnrich Company API", slug: "dataenrich-company",
        description: "Enrich any company domain or email with firmographic data: industry, size, funding, tech stack, and more.",
        longDescription: "DataEnrich pulls from a database of 50M+ companies updated weekly. Pass a domain, email, or company name. Returns: company name, description, industry, employee count, annual revenue, funding rounds, HQ location, tech stack (from web scraping), and social profiles.",
        baseUrl: "https://api.dataenrich.io/v1",
        version: "1.4.0", category: apiCategories[4], categoryId: "ac5",
        tags: at([0, 2, 6, 7, 8]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 1, teamPrice: 3, enterprisePrice: 10,
        freeCallsPerMonth: 100,
        endpoints: [
            { method: "GET", path: "/company", description: "Enrich by domain or company name" },
            { method: "GET", path: "/email", description: "Enrich by email address" },
            { method: "POST", path: "/bulk", description: "Batch enrich up to 1000 records" },
        ],
        documentation: "GET /company?domain=stripe.com — returns full firmographic JSON.",
        codeSnippet: `const res = await fetch('https://api.dataenrich.io/v1/company?domain=stripe.com', {\n  headers: { 'X-API-Key': process.env.DE_KEY },\n});\nconst company = await res.json();\n// { name: 'Stripe', industry: 'Fintech', employees: 8000, funding: '$9.4B', tech: ['React', 'Go', 'AWS'] }`,
        status: "PUBLISHED", featured: false,
        callCount: 4_400_000, averageRating: 4.6, reviewCount: 132,
        uptime: 99.88, latencyMs: 280,
        creator: apiUsers[1], creatorId: "au2", createdAt: "2024-04-15", updatedAt: "2024-11-20",
    },
    {
        id: "api17", name: "ClickStream Analytics API", slug: "clickstream-analytics",
        description: "Ingest billions of user events and query real-time analytics with SQL-style filters in under 1 second.",
        longDescription: "ClickStream is an event ingestion + real-time analytics engine. Send any event (pageview, click, conversion) via the REST API or SDK. Query aggregations (count, unique users, funnels, retention) with a simple filter JSON. Supports product analytics, A/B experiment results, and custom dashboards.",
        baseUrl: "https://api.clickstream.io/v2",
        version: "2.5.0", category: apiCategories[4], categoryId: "ac5",
        tags: at([0, 2, 5, 6, 7]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 49, teamPrice: 149, enterprisePrice: 599,
        freeCallsPerMonth: 100000,
        endpoints: [
            { method: "POST", path: "/events", description: "Ingest one or a batch of events" },
            { method: "POST", path: "/query", description: "Query analytics with filter JSON" },
            { method: "GET", path: "/funnels/:id", description: "Get funnel conversion rates" },
            { method: "GET", path: "/retention", description: "Day-N retention cohort data" },
        ],
        documentation: "POST events with user_id, event_name, and properties. Query with /query for aggregations.",
        codeSnippet: `// Track an event\nawait fetch('https://api.clickstream.io/v2/events', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.CS_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ user_id: 'u_123', event: 'component_viewed', props: { slug: 'aurora-hero' } }),\n});\n\n// Query total views in last 7d\nconst { count } = await (await fetch('https://api.clickstream.io/v2/query', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.CS_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ event: 'component_viewed', period: '7d', aggregate: 'count' }),\n})).json();`,
        status: "PUBLISHED", featured: true,
        callCount: 2_800_000_000, averageRating: 4.8, reviewCount: 189,
        uptime: 99.95, latencyMs: 18,
        creator: apiUsers[0], creatorId: "au1", createdAt: "2024-02-20", updatedAt: "2024-12-12",
    },
    {
        id: "api18", name: "WebScraper Pro API", slug: "webscraper-pro",
        description: "Scrape any website with headless Chrome, JS rendering, and smart data extraction — no captcha blocks.",
        longDescription: "WebScraper Pro handles bot detection, rotating proxies, CAPTCHA solving, and JavaScript rendering automatically. Extract structured data using CSS selectors or our AI-powered schema extractor. Supports pagination, session/cookie handling, and scheduled recurring scrapes.",
        baseUrl: "https://api.webscraperpro.io/v1",
        version: "1.7.0", category: apiCategories[4], categoryId: "ac5",
        tags: at([0, 2, 5, 6, 7]),
        authType: "API_KEY", pricingModel: "PAY_PER_CALL",
        price: 5, teamPrice: 15, enterprisePrice: 49,
        freeCallsPerMonth: 100,
        endpoints: [
            { method: "POST", path: "/scrape", description: "Scrape a URL and return HTML or extracted data" },
            { method: "POST", path: "/extract", description: "AI-powered schema extraction from a URL" },
            { method: "POST", path: "/screenshot", description: "Take a full-page screenshot" },
            { method: "POST", path: "/jobs", description: "Schedule recurring scrape jobs" },
        ],
        documentation: "POST a url and optional selector or schema. Returns scraped HTML or structured JSON.",
        codeSnippet: `const res = await fetch('https://api.webscraperpro.io/v1/scrape', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.WSP_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({\n    url: 'https://news.ycombinator.com',\n    extract: { selector: '.titleline > a', multiple: true, field: 'title' },\n    js_render: true,\n  }),\n});\nconst { results } = await res.json(); // [{ title: 'Show HN: ...' }, ...]`,
        status: "PUBLISHED", featured: false,
        callCount: 6_200_000, averageRating: 4.5, reviewCount: 167,
        uptime: 99.8, latencyMs: 3500,
        creator: apiUsers[1], creatorId: "au2", createdAt: "2024-05-20", updatedAt: "2024-11-30",
    },

    // ── Maps & Location ──────────────────────────────────────────────────────
    {
        id: "api19", name: "GeoSmart Maps API", slug: "geosmart-maps",
        description: "Geocoding, reverse geocoding, routing, isochrones, and place search for 200+ countries.",
        longDescription: "GeoSmart covers the full location intelligence stack. Forward/reverse geocode with 5m accuracy. Point-to-point routing with traffic-aware ETAs for driving, cycling, and walking. Isochrone (reachability) polygons for market analysis. Autocomplete place search returning lat/lng and metadata.",
        baseUrl: "https://api.geosmart.io/v1",
        version: "1.8.0", category: apiCategories[5], categoryId: "ac6",
        tags: at([0, 2, 6, 7, 8]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 29, teamPrice: 79, enterprisePrice: 299,
        freeCallsPerMonth: 25000,
        endpoints: [
            { method: "GET", path: "/geocode", description: "Forward geocode an address" },
            { method: "GET", path: "/reverse", description: "Reverse geocode lat/lng" },
            { method: "POST", path: "/route", description: "Point-to-point routing" },
            { method: "POST", path: "/isochrone", description: "Reachability polygon for a point + time" },
            { method: "GET", path: "/places/search", description: "Autocomplete place search" },
        ],
        documentation: "GET /geocode?address=1600+Amphitheatre+Pkwy — returns lat, lng, and formatted address.",
        codeSnippet: `// Geocode an address\nconst res = await fetch(\n  \`https://api.geosmart.io/v1/geocode?address=\${encodeURIComponent('1 Infinite Loop, Cupertino')}\`,\n  { headers: { 'X-API-Key': process.env.GEO_KEY } }\n);\nconst { lat, lng, formatted } = await res.json();\n\n// Traffic-aware route\nconst route = await fetch('https://api.geosmart.io/v1/route', {\n  method: 'POST',\n  headers: { 'X-API-Key': process.env.GEO_KEY, 'Content-Type': 'application/json' },\n  body: JSON.stringify({ origin: [37.3318, -122.0312], destination: [37.7749, -122.4194], mode: 'driving' }),\n});\nconst { distance_km, duration_min } = await route.json();`,
        status: "PUBLISHED", featured: true,
        callCount: 8_900_000, averageRating: 4.8, reviewCount: 254,
        uptime: 99.97, latencyMs: 55,
        creator: apiUsers[0], creatorId: "au1", createdAt: "2024-03-15", updatedAt: "2024-12-14",
    },
    {
        id: "api20", name: "IPInsight Geo & Threat API", slug: "ipinsight-geo-threat",
        description: "IP geolocation, ASN lookup, VPN/proxy/TOR detection, and threat scoring for any IPv4 or IPv6 address.",
        longDescription: "IPInsight returns country, region, city, postal code, timezone, and currency for any IP across 250k unique ASNs. Threat intelligence flags VPN, proxy, TOR exit nodes, data center IPs, and abusive sources. Useful for geo-fencing content, fraud detection, and access control.",
        baseUrl: "https://api.ipinsight.io/v1",
        version: "1.3.0", category: apiCategories[5], categoryId: "ac6",
        tags: at([0, 2, 6, 7, 8]),
        authType: "API_KEY", pricingModel: "FREEMIUM",
        price: 9, teamPrice: 29, enterprisePrice: 99,
        freeCallsPerMonth: 30000,
        endpoints: [
            { method: "GET", path: "/:ip", description: "Full geo + threat data for an IP" },
            { method: "GET", path: "/:ip/geo", description: "Geo data only (country, city, TZ)" },
            { method: "GET", path: "/:ip/threat", description: "Threat intelligence only (VPN, proxy)" },
            { method: "POST", path: "/batch", description: "Batch lookup up to 100 IPs" },
        ],
        documentation: "GET /:ip with your API key header. Returns JSON with geo and threat fields.",
        codeSnippet: `const res = await fetch('https://api.ipinsight.io/v1/8.8.8.8', {\n  headers: { 'X-API-Key': process.env.IPI_KEY },\n});\nconst data = await res.json();\n// {\n//   ip: '8.8.8.8', country: 'US', city: 'Mountain View',\n//   timezone: 'America/Los_Angeles',\n//   threat: { is_vpn: false, is_proxy: false, risk_score: 3 }\n// }`,
        status: "PUBLISHED", featured: false,
        callCount: 32_000_000, averageRating: 4.7, reviewCount: 198,
        uptime: 99.98, latencyMs: 12,
        creator: apiUsers[0], creatorId: "au1", createdAt: "2024-04-01", updatedAt: "2024-12-01",
    },
];
