import { User, Category, ComponentItem, Review, Testimonial, BlogPost, Coupon, Purchase } from "@/types";

const avatarBase = "https://api.dicebear.com/7.x/avataaars/svg?seed=";

export const users: User[] = [
    { id: "u1", name: "Alex Rivera", email: "alex@example.com", image: `${avatarBase}alex`, role: "SELLER", bio: "Senior UI Engineer with 10+ years of experience building design systems.", website: "https://alexrivera.dev", githubUrl: "https://github.com", twitterUrl: "https://twitter.com", createdAt: "2024-01-15" },
    { id: "u2", name: "Sarah Chen", email: "sarah@example.com", image: `${avatarBase}sarah`, role: "SELLER", bio: "Design system architect. Former Figma, now independent.", website: "https://sarahchen.io", githubUrl: "https://github.com", twitterUrl: "https://twitter.com", createdAt: "2024-02-01" },
    { id: "u3", name: "Marcus Johnson", email: "marcus@example.com", image: `${avatarBase}marcus`, role: "SELLER", bio: "Full-stack developer specialized in React and Next.js.", createdAt: "2024-03-10" },
    { id: "u4", name: "Emily Park", email: "emily@example.com", image: `${avatarBase}emily`, role: "SELLER", bio: "Creative developer building beautiful web experiences.", createdAt: "2024-01-20" },
    { id: "u5", name: "David Kim", email: "david@example.com", image: `${avatarBase}david`, role: "SELLER", bio: "UI/UX designer turned developer.", createdAt: "2024-04-05" },
    { id: "u6", name: "Lisa Wang", email: "lisa@example.com", image: `${avatarBase}lisa`, role: "USER", createdAt: "2024-05-01" },
    { id: "u7", name: "James Wilson", email: "james@example.com", image: `${avatarBase}james`, role: "USER", createdAt: "2024-05-15" },
    { id: "u8", name: "Admin User", email: "admin@componentvault.com", image: `${avatarBase}admin`, role: "ADMIN", createdAt: "2024-01-01" },
];

export const categories: Category[] = [
    { id: "c1", name: "Hero Sections", slug: "hero-sections", icon: "🎯", description: "Stunning hero sections with animations", componentCount: 12 },
    { id: "c2", name: "Navigation Bars", slug: "navigation-bars", icon: "🧭", description: "Modern responsive navbars", componentCount: 8 },
    { id: "c3", name: "Dashboards", slug: "dashboards", icon: "📊", description: "Complete dashboard layouts", componentCount: 15 },
    { id: "c4", name: "Forms", slug: "forms", icon: "📝", description: "Beautiful form components", componentCount: 10 },
    { id: "c5", name: "Cards", slug: "cards", icon: "🃏", description: "Versatile card components", componentCount: 14 },
    { id: "c6", name: "Modals", slug: "modals", icon: "💬", description: "Elegant modal dialogs", componentCount: 6 },
    { id: "c7", name: "Sidebars", slug: "sidebars", icon: "📑", description: "Collapsible sidebar layouts", componentCount: 7 },
    { id: "c8", name: "Landing Pages", slug: "landing-pages", icon: "🚀", description: "Full landing page templates", componentCount: 9 },
    { id: "c9", name: "Authentication Pages", slug: "authentication-pages", icon: "🔐", description: "Login, register, and auth flows", componentCount: 8 },
    { id: "c10", name: "Pricing Tables", slug: "pricing-tables", icon: "💰", description: "Pricing comparison tables", componentCount: 5 },
    { id: "c11", name: "Footers", slug: "footers", icon: "🦶", description: "Feature-rich footer sections", componentCount: 6 },
    { id: "c12", name: "Data Tables", slug: "data-tables", icon: "📋", description: "Sortable, filterable data tables", componentCount: 8 },
    { id: "c13", name: "Charts", slug: "charts", icon: "📈", description: "Interactive chart components", componentCount: 7 },
    { id: "c14", name: "E-commerce Components", slug: "e-commerce", icon: "🛒", description: "Shopping carts, product cards", componentCount: 11 },
    { id: "c15", name: "Blog Templates", slug: "blog-templates", icon: "✍️", description: "Blog layouts and post templates", componentCount: 6 },
    { id: "c16", name: "Animation Components", slug: "animation-components", icon: "✨", description: "Micro-interactions and animations", componentCount: 9 },
    { id: "c17", name: "3D Components", slug: "3d-components", icon: "🎮", description: "Three.js and WebGL components", componentCount: 7 },
    { id: "c18", name: "3D Spline Models", slug: "3d-spline-models", icon: "🤖", description: "Ready-to-embed interactive Spline 3D scenes", componentCount: 10 },
    { id: "c19", name: "APIs & Integrations", slug: "apis-integrations", icon: "⚡", description: "Ready-to-use API wrappers and SDK integrations", componentCount: 12 },
    { id: "c20", name: "Security & Antivirus", slug: "security-antivirus", icon: "🛡️", description: "Antivirus engines, threat scanners and security UI", componentCount: 8 },
    { id: "c21", name: "Printers & Hardware", slug: "printers-hardware", icon: "🖨️", description: "Printer SDKs, receipt printers and hardware tools", componentCount: 6 },
];

const tagPool = [
    { id: "t1", name: "React" }, { id: "t2", name: "Next.js" }, { id: "t3", name: "TypeScript" },
    { id: "t4", name: "Tailwind" }, { id: "t5", name: "Framer Motion" }, { id: "t6", name: "Responsive" },
    { id: "t7", name: "Dark Mode" }, { id: "t8", name: "Accessible" }, { id: "t9", name: "Animated" },
    { id: "t10", name: "SSR Ready" },
    { id: "t11", name: "Three.js" }, { id: "t12", name: "Spline" }, { id: "t13", name: "WebGL" },
    { id: "t14", name: "REST API" }, { id: "t15", name: "SDK" }, { id: "t16", name: "Webhooks" },
    { id: "t17", name: "Security" }, { id: "t18", name: "Antivirus" }, { id: "t19", name: "Printer" },
    { id: "t20", name: "Hardware" }, { id: "t21", name: "Node.js" }, { id: "t22", name: "Interactive" },
];

function makeTags(indices: number[]) { return indices.map(i => tagPool[i]); }

export const components: ComponentItem[] = [
    { id: "comp1", name: "Aurora Hero Section", slug: "aurora-hero-section", description: "A breathtaking hero section with aurora borealis animated gradient background, floating particles, and smooth text reveal animations.", longDescription: "Transform your landing page with this stunning Aurora Hero Section. Features include animated gradient mesh backgrounds, particle effects, typewriter text animations, and responsive CTA buttons with hover effects.", price: 149, teamPrice: 299, enterprisePrice: 499, category: categories[0], categoryId: "c1", tags: makeTags([0, 1, 3, 4, 8]), images: ["/placeholder.svg"], fileUrl: "/files/aurora-hero.zip", documentation: "Install via npm, import AuroraHero from the package.", version: "2.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3421, averageRating: 4.8, reviewCount: 127, creator: users[0], creatorId: "u1", createdAt: "2024-06-15", updatedAt: "2024-12-01" },
    { id: "comp2", name: "Glass Navigation Bar", slug: "glass-navigation-bar", description: "A frosted glass-effect navigation bar with smooth scroll behavior and mobile hamburger menu.", price: 99, teamPrice: 199, enterprisePrice: 399, category: categories[1], categoryId: "c2", tags: makeTags([0, 1, 3, 5, 6]), images: ["/placeholder.svg"], fileUrl: "/files/glass-nav.zip", version: "1.4.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 5102, averageRating: 4.9, reviewCount: 203, creator: users[1], creatorId: "u2", createdAt: "2024-05-20", updatedAt: "2024-11-15" },
    { id: "comp3", name: "Analytics Dashboard Pro", slug: "analytics-dashboard-pro", description: "A complete analytics dashboard with real-time charts, KPI cards, and data visualization widgets.", price: 299, teamPrice: 399, enterprisePrice: 599, category: categories[2], categoryId: "c3", tags: makeTags([0, 1, 2, 3, 6]), images: ["/placeholder.svg"], fileUrl: "/files/analytics-dash.zip", version: "3.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2847, averageRating: 4.7, reviewCount: 98, creator: users[0], creatorId: "u1", createdAt: "2024-07-01", updatedAt: "2024-12-10" },
    { id: "comp4", name: "Multi-Step Form Wizard", slug: "multi-step-form-wizard", description: "An elegant multi-step form with progress indicator, validation, and smooth step transitions.", price: 129, teamPrice: 249, enterprisePrice: 449, category: categories[3], categoryId: "c4", tags: makeTags([0, 2, 3, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/form-wizard.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1893, averageRating: 4.6, reviewCount: 72, creator: users[2], creatorId: "u3", createdAt: "2024-08-10", updatedAt: "2024-11-20" },
    { id: "comp5", name: "Holographic Card Stack", slug: "holographic-card-stack", description: "Interactive 3D holographic cards with tilt effects, gradient borders, and stacking animations.", price: 179, teamPrice: 329, enterprisePrice: 549, category: categories[4], categoryId: "c5", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/holo-cards.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4210, averageRating: 4.9, reviewCount: 156, creator: users[3], creatorId: "u4", createdAt: "2024-04-15", updatedAt: "2024-10-30" },
    { id: "comp6", name: "Command Palette Modal", slug: "command-palette-modal", description: "A Spotlight/CMD+K style command palette with fuzzy search, keyboard navigation, and grouped actions.", price: 119, teamPrice: 229, enterprisePrice: 429, category: categories[5], categoryId: "c6", tags: makeTags([0, 1, 2, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/cmd-palette.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2156, averageRating: 4.8, reviewCount: 89, creator: users[1], creatorId: "u2", createdAt: "2024-06-01", updatedAt: "2024-11-05" },
    { id: "comp7", name: "Collapsible Sidebar Pro", slug: "collapsible-sidebar-pro", description: "A feature-rich collapsible sidebar with nested menus, tooltips, and smooth animations.", price: 159, teamPrice: 299, enterprisePrice: 499, category: categories[6], categoryId: "c7", tags: makeTags([0, 1, 3, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/sidebar-pro.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1654, averageRating: 4.5, reviewCount: 63, creator: users[4], creatorId: "u5", createdAt: "2024-09-01", updatedAt: "2024-12-05" },
    { id: "comp8", name: "SaaS Landing Page Kit", slug: "saas-landing-page-kit", description: "A complete SaaS landing page with hero, features, pricing, testimonials, and FAQ sections.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[7], categoryId: "c8", tags: makeTags([0, 1, 3, 4, 5]), images: ["/placeholder.svg"], fileUrl: "/files/saas-landing.zip", version: "2.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 6234, averageRating: 4.9, reviewCount: 234, creator: users[0], creatorId: "u1", createdAt: "2024-03-01", updatedAt: "2024-12-12" },
    { id: "comp9", name: "Neon Auth Pages", slug: "neon-auth-pages", description: "Authentication pages with neon glow effects, animated backgrounds, and social login integration.", price: 139, teamPrice: 269, enterprisePrice: 469, category: categories[8], categoryId: "c9", tags: makeTags([0, 1, 3, 6, 8]), images: ["/placeholder.svg"], fileUrl: "/files/neon-auth.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2987, averageRating: 4.7, reviewCount: 105, creator: users[3], creatorId: "u4", createdAt: "2024-07-20", updatedAt: "2024-11-25" },
    { id: "comp10", name: "Gradient Pricing Table", slug: "gradient-pricing-table", description: "A modern pricing table with gradient accents, feature comparison, and toggle animations.", price: 99, teamPrice: 199, enterprisePrice: 399, category: categories[9], categoryId: "c10", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/pricing-table.zip", version: "1.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3876, averageRating: 4.8, reviewCount: 142, creator: users[2], creatorId: "u3", createdAt: "2024-05-10", updatedAt: "2024-12-08" },
    { id: "comp11", name: "Mega Footer Component", slug: "mega-footer-component", description: "A comprehensive footer with newsletter signup, sitemap, social links, and dark/light variants.", price: 99, teamPrice: 199, enterprisePrice: 349, category: categories[10], categoryId: "c11", tags: makeTags([0, 3, 5, 6, 7]), images: ["/placeholder.svg"], fileUrl: "/files/mega-footer.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1432, averageRating: 4.4, reviewCount: 48, creator: users[4], creatorId: "u5", createdAt: "2024-10-01", updatedAt: "2024-12-01" },
    { id: "comp12", name: "Advanced Data Table", slug: "advanced-data-table", description: "A powerful data table with sorting, filtering, pagination, row selection, and column resizing.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[11], categoryId: "c12", tags: makeTags([0, 1, 2, 3, 7]), images: ["/placeholder.svg"], fileUrl: "/files/data-table.zip", version: "2.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4567, averageRating: 4.8, reviewCount: 178, creator: users[1], creatorId: "u2", createdAt: "2024-04-01", updatedAt: "2024-12-15" },
    { id: "comp13", name: "Interactive Chart Suite", slug: "interactive-chart-suite", description: "A collection of beautiful, interactive charts including line, bar, pie, area, and radar charts.", price: 229, teamPrice: 379, enterprisePrice: 579, category: categories[12], categoryId: "c13", tags: makeTags([0, 2, 3, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/chart-suite.zip", version: "1.8.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2345, averageRating: 4.6, reviewCount: 87, creator: users[0], creatorId: "u1", createdAt: "2024-08-01", updatedAt: "2024-11-30" },
    { id: "comp14", name: "E-commerce Product Grid", slug: "e-commerce-product-grid", description: "A complete product listing grid with filters, quick view, cart integration, and wishlist support.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[13], categoryId: "c14", tags: makeTags([0, 1, 3, 5, 9]), images: ["/placeholder.svg"], fileUrl: "/files/product-grid.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3211, averageRating: 4.7, reviewCount: 115, creator: users[2], creatorId: "u3", createdAt: "2024-06-20", updatedAt: "2024-12-05" },
    { id: "comp15", name: "Minimal Blog Layout", slug: "minimal-blog-layout", description: "A clean, minimal blog layout with MDX support, table of contents, and reading progress bar.", price: 149, teamPrice: 279, enterprisePrice: 479, category: categories[14], categoryId: "c15", tags: makeTags([0, 1, 3, 5, 6]), images: ["/placeholder.svg"], fileUrl: "/files/blog-layout.zip", version: "1.6.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1876, averageRating: 4.5, reviewCount: 67, creator: users[3], creatorId: "u4", createdAt: "2024-09-15", updatedAt: "2024-11-20" },
    { id: "comp16", name: "Scroll Animation Kit", slug: "scroll-animation-kit", description: "A collection of scroll-triggered animations including reveal, parallax, and stagger effects.", price: 169, teamPrice: 309, enterprisePrice: 509, category: categories[15], categoryId: "c16", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/scroll-anims.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 5678, averageRating: 4.9, reviewCount: 198, creator: users[1], creatorId: "u2", createdAt: "2024-03-15", updatedAt: "2024-12-10" },
    { id: "comp17", name: "3D Card Showcase", slug: "3d-card-showcase", description: "Interactive 3D card component with mouse-tracking tilt, lighting effects, and reflection.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[16], categoryId: "c17", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/3d-cards.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1234, averageRating: 4.7, reviewCount: 43, creator: users[4], creatorId: "u5", createdAt: "2024-10-10", updatedAt: "2024-12-01" },
    { id: "comp18", name: "Notification Center", slug: "notification-center", description: "A beautiful notification center with grouped notifications, actions, and dismissal animations.", price: 119, teamPrice: 229, enterprisePrice: 429, category: categories[5], categoryId: "c6", tags: makeTags([0, 1, 3, 4, 7]), images: ["/placeholder.svg"], fileUrl: "/files/notif-center.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1567, averageRating: 4.5, reviewCount: 54, creator: users[2], creatorId: "u3", createdAt: "2024-08-25", updatedAt: "2024-11-15" },
    { id: "comp19", name: "Kanban Board", slug: "kanban-board", description: "A drag-and-drop Kanban board with swimlanes, labels, assignees, and due dates.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[2], categoryId: "c3", tags: makeTags([0, 1, 2, 3, 8]), images: ["/placeholder.svg"], fileUrl: "/files/kanban.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3456, averageRating: 4.8, reviewCount: 134, creator: users[0], creatorId: "u1", createdAt: "2024-05-01", updatedAt: "2024-12-15" },
    { id: "comp20", name: "Checkout Flow Kit", slug: "checkout-flow-kit", description: "A complete multi-step checkout flow with cart, shipping, payment, and confirmation pages.", price: 279, teamPrice: 449, enterprisePrice: 599, category: categories[13], categoryId: "c14", tags: makeTags([0, 1, 2, 3, 5]), images: ["/placeholder.svg"], fileUrl: "/files/checkout-kit.zip", version: "1.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2789, averageRating: 4.7, reviewCount: 101, creator: users[3], creatorId: "u4", createdAt: "2024-07-10", updatedAt: "2024-12-08" },

    // ── 50 additional components ─────────────────────────────────────────────
    { id: "comp21", name: "Particle Hero Banner", slug: "particle-hero-banner", description: "Dynamic hero section with interactive WebGL particle system, mouse-tracking, and gradient overlays.", price: 189, teamPrice: 349, enterprisePrice: 549, category: categories[0], categoryId: "c1", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/particle-hero.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2180, averageRating: 4.9, reviewCount: 84, creator: users[1], creatorId: "u2", createdAt: "2024-08-01", updatedAt: "2024-12-10" },
    { id: "comp22", name: "Typewriter Hero", slug: "typewriter-hero", description: "Cinematic hero section with multi-phrase typewriter effect, animated cursor, and fullscreen video background support.", price: 129, teamPrice: 249, enterprisePrice: 449, category: categories[0], categoryId: "c1", tags: makeTags([0, 1, 4, 8, 5]), images: ["/placeholder.svg"], fileUrl: "/files/typewriter-hero.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1870, averageRating: 4.7, reviewCount: 63, creator: users[2], creatorId: "u3", createdAt: "2024-09-10", updatedAt: "2024-12-01" },
    { id: "comp23", name: "Split-Screen Hero", slug: "split-screen-hero", description: "Bold split-screen hero layout with high-contrast typography and animated image/illustration pane.", price: 149, teamPrice: 279, enterprisePrice: 479, category: categories[0], categoryId: "c1", tags: makeTags([0, 3, 5, 6, 8]), images: ["/placeholder.svg"], fileUrl: "/files/split-hero.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1440, averageRating: 4.6, reviewCount: 52, creator: users[4], creatorId: "u5", createdAt: "2024-10-05", updatedAt: "2024-11-28" },

    { id: "comp24", name: "Mega Menu Navbar", slug: "mega-menu-navbar", description: "Enterprise-grade navigation with mega dropdown menus, search bar, and role-based items.", price: 179, teamPrice: 329, enterprisePrice: 529, category: categories[1], categoryId: "c2", tags: makeTags([0, 1, 2, 5, 7]), images: ["/placeholder.svg"], fileUrl: "/files/mega-nav.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3240, averageRating: 4.8, reviewCount: 118, creator: users[0], creatorId: "u1", createdAt: "2024-06-20", updatedAt: "2024-12-12" },
    { id: "comp25", name: "Sticky Tabbed Nav", slug: "sticky-tabbed-nav", description: "A sticky multi-tab navigation bar with active indicator animations and scroll-spy functionality.", price: 99, teamPrice: 199, enterprisePrice: 399, category: categories[1], categoryId: "c2", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/sticky-tabs.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2110, averageRating: 4.7, reviewCount: 79, creator: users[3], creatorId: "u4", createdAt: "2024-07-15", updatedAt: "2024-11-20" },

    { id: "comp26", name: "CRM Dashboard", slug: "crm-dashboard", description: "Full-featured CRM dashboard with contact lists, deal pipelines, activity timeline, and email integration.", price: 349, teamPrice: 499, enterprisePrice: 699, category: categories[2], categoryId: "c3", tags: makeTags([0, 1, 2, 3, 6]), images: ["/placeholder.svg"], fileUrl: "/files/crm-dash.zip", version: "2.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1980, averageRating: 4.8, reviewCount: 76, creator: users[1], creatorId: "u2", createdAt: "2024-05-10", updatedAt: "2024-12-15" },
    { id: "comp27", name: "Finance Dashboard", slug: "finance-dashboard", description: "Real-time finance dashboard with portfolio tracker, candlestick charts, P&L panels, and crypto widgets.", price: 329, teamPrice: 479, enterprisePrice: 679, category: categories[2], categoryId: "c3", tags: makeTags([0, 2, 3, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/finance-dash.zip", version: "1.4.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2340, averageRating: 4.9, reviewCount: 92, creator: users[0], creatorId: "u1", createdAt: "2024-04-20", updatedAt: "2024-12-08" },
    { id: "comp28", name: "Project Management Board", slug: "project-management-board", description: "Jira-like project board with sprint planning, burn-down charts, backlog view, and team workload heat map.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[2], categoryId: "c3", tags: makeTags([0, 1, 2, 5, 7]), images: ["/placeholder.svg"], fileUrl: "/files/project-board.zip", version: "3.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2870, averageRating: 4.8, reviewCount: 110, creator: users[2], creatorId: "u3", createdAt: "2024-03-15", updatedAt: "2024-12-10" },

    { id: "comp29", name: "OTP Verification Form", slug: "otp-verification-form", description: "A slick OTP input with auto-focus, paste detection, shake-on-error animation, and countdown resend.", price: 89, teamPrice: 179, enterprisePrice: 379, category: categories[3], categoryId: "c4", tags: makeTags([0, 2, 3, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/otp-form.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2560, averageRating: 4.8, reviewCount: 95, creator: users[4], creatorId: "u5", createdAt: "2024-09-01", updatedAt: "2024-11-25" },
    { id: "comp30", name: "File Upload Dropzone", slug: "file-upload-dropzone", description: "Drag-and-drop file uploader with preview tiles, progress bars, multiple file support, and validation.", price: 119, teamPrice: 229, enterprisePrice: 429, category: categories[3], categoryId: "c4", tags: makeTags([0, 1, 3, 5, 7]), images: ["/placeholder.svg"], fileUrl: "/files/dropzone.zip", version: "2.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3120, averageRating: 4.9, reviewCount: 133, creator: users[1], creatorId: "u2", createdAt: "2024-06-12", updatedAt: "2024-12-01" },
    { id: "comp31", name: "Rich Text Editor", slug: "rich-text-editor", description: "A beautiful Notion-inspired rich text editor with slash commands, image blocks, and real-time collaboration hooks.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[3], categoryId: "c4", tags: makeTags([0, 1, 2, 3, 9]), images: ["/placeholder.svg"], fileUrl: "/files/rich-editor.zip", version: "1.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1680, averageRating: 4.7, reviewCount: 67, creator: users[3], creatorId: "u4", createdAt: "2024-10-20", updatedAt: "2024-12-14" },

    { id: "comp32", name: "Glassmorphic Profile Card", slug: "glass-profile-card", description: "Ultra-premium profile card with glassmorphism, parallax on hover, social stats, and skill progress bars.", price: 79, teamPrice: 149, enterprisePrice: 299, category: categories[4], categoryId: "c5", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/glass-card.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 4100, averageRating: 4.9, reviewCount: 162, creator: users[0], creatorId: "u1", createdAt: "2024-05-25", updatedAt: "2024-11-15" },
    { id: "comp33", name: "Flip Product Card", slug: "flip-product-card", description: "CSS perspective flip card with product image front, detailed specs on the back, and add-to-cart animation.", price: 69, teamPrice: 139, enterprisePrice: 279, category: categories[4], categoryId: "c5", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/flip-card.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2890, averageRating: 4.7, reviewCount: 108, creator: users[2], creatorId: "u3", createdAt: "2024-08-18", updatedAt: "2024-12-03" },
    { id: "comp34", name: "Testimonial Carousel Card", slug: "testimonial-carousel-card", description: "Auto-playing testimonial cards with avatar, star rating, company logo, and swipe gesture support.", price: 89, teamPrice: 169, enterprisePrice: 349, category: categories[4], categoryId: "c5", tags: makeTags([0, 3, 4, 5, 9]), images: ["/placeholder.svg"], fileUrl: "/files/testimonial-card.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2200, averageRating: 4.6, reviewCount: 89, creator: users[4], creatorId: "u5", createdAt: "2024-09-22", updatedAt: "2024-11-30" },

    { id: "comp35", name: "Image Lightbox Modal", slug: "image-lightbox-modal", description: "A beautiful fullscreen image lightbox with zoom, keyboard navigation, thumbnail strip, and swipe gestures.", price: 109, teamPrice: 209, enterprisePrice: 409, category: categories[5], categoryId: "c6", tags: makeTags([0, 3, 4, 5, 7]), images: ["/placeholder.svg"], fileUrl: "/files/lightbox.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1870, averageRating: 4.7, reviewCount: 72, creator: users[1], creatorId: "u2", createdAt: "2024-08-05", updatedAt: "2024-11-20" },
    { id: "comp36", name: "Confirmation Dialog", slug: "confirmation-dialog", description: "Animated confirmation dialogs with destructive actions, countdown timer, and undo functionality.", price: 69, teamPrice: 139, enterprisePrice: 279, category: categories[5], categoryId: "c6", tags: makeTags([0, 2, 3, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/confirm-dialog.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2430, averageRating: 4.8, reviewCount: 93, creator: users[3], creatorId: "u4", createdAt: "2024-10-12", updatedAt: "2024-12-05" },

    { id: "comp37", name: "AI Side Panel", slug: "ai-side-panel", description: "ChatGPT-style collapsible side panel with message history, streaming text, code highlighting, and copy button.", price: 229, teamPrice: 379, enterprisePrice: 579, category: categories[6], categoryId: "c7", tags: makeTags([0, 1, 2, 3, 8]), images: ["/placeholder.svg"], fileUrl: "/files/ai-panel.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3450, averageRating: 4.9, reviewCount: 141, creator: users[0], creatorId: "u1", createdAt: "2024-04-10", updatedAt: "2024-12-14" },
    { id: "comp38", name: "Context Menu Sidebar", slug: "context-menu-sidebar", description: "Resizable sidebar with right-click context menu, drag-and-drop tree navigation, and icon support.", price: 159, teamPrice: 299, enterprisePrice: 499, category: categories[6], categoryId: "c7", tags: makeTags([0, 1, 3, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/context-sidebar.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1290, averageRating: 4.6, reviewCount: 48, creator: users[2], creatorId: "u3", createdAt: "2024-10-01", updatedAt: "2024-12-01" },

    { id: "comp39", name: "Agency Portfolio Template", slug: "agency-portfolio", description: "Stunning agency portfolio with case studies grid, cursor effects, award badges, and dark/light toggle.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[7], categoryId: "c8", tags: makeTags([0, 1, 3, 4, 8]), images: ["/placeholder.svg"], fileUrl: "/files/agency-portfolio.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4230, averageRating: 4.9, reviewCount: 169, creator: users[1], creatorId: "u2", createdAt: "2024-03-20", updatedAt: "2024-12-12" },
    { id: "comp40", name: "App Download Landing Page", slug: "app-download-landing", description: "Mobile app landing page with device mockup parallax, feature carousel, download badge buttons, and App Store ratings.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[7], categoryId: "c8", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/app-landing.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2870, averageRating: 4.8, reviewCount: 107, creator: users[4], creatorId: "u5", createdAt: "2024-06-05", updatedAt: "2024-11-22" },
    { id: "comp41", name: "Startup Launch Page", slug: "startup-launch-page", description: "Waitlist landing page with email capture, countdown timer, animated background, and social share buttons.", price: 179, teamPrice: 329, enterprisePrice: 529, category: categories[7], categoryId: "c8", tags: makeTags([0, 1, 3, 4, 5]), images: ["/placeholder.svg"], fileUrl: "/files/launch-page.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3780, averageRating: 4.8, reviewCount: 148, creator: users[3], creatorId: "u4", createdAt: "2024-07-25", updatedAt: "2024-12-08" },

    { id: "comp42", name: "Magic Link Auth", slug: "magic-link-auth", description: "Passwordless magic link authentication flow: email input, sent confirmation, and expiring link verification.", price: 149, teamPrice: 279, enterprisePrice: 479, category: categories[8], categoryId: "c9", tags: makeTags([0, 1, 2, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/magic-link.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2150, averageRating: 4.7, reviewCount: 81, creator: users[0], creatorId: "u1", createdAt: "2024-08-15", updatedAt: "2024-11-28" },
    { id: "comp43", name: "Two-Factor Auth Flow", slug: "two-factor-auth-flow", description: "Complete 2FA setup flow with QR code generator, authenticator app pairing, backup codes, and recovery.", price: 169, teamPrice: 309, enterprisePrice: 509, category: categories[8], categoryId: "c9", tags: makeTags([0, 2, 3, 7, 9]), images: ["/placeholder.svg"], fileUrl: "/files/2fa-flow.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1870, averageRating: 4.9, reviewCount: 74, creator: users[2], creatorId: "u3", createdAt: "2024-09-25", updatedAt: "2024-12-10" },

    { id: "comp44", name: "Usage-Based Pricing Table", slug: "usage-based-pricing", description: "Interactive pricing calculator with sliders for usage tiers, live cost updates, and feature breakdown grid.", price: 129, teamPrice: 249, enterprisePrice: 449, category: categories[9], categoryId: "c10", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/usage-pricing.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2890, averageRating: 4.8, reviewCount: 112, creator: users[1], creatorId: "u2", createdAt: "2024-07-08", updatedAt: "2024-12-01" },
    { id: "comp45", name: "Annual vs Monthly Toggle", slug: "annual-monthly-toggle", description: "Billing period toggle with animated savings badge, cross-out pricing, and confetti on annual plan select.", price: 89, teamPrice: 169, enterprisePrice: 349, category: categories[9], categoryId: "c10", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/billing-toggle.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2340, averageRating: 4.7, reviewCount: 88, creator: users[4], creatorId: "u5", createdAt: "2024-09-10", updatedAt: "2024-11-15" },

    { id: "comp46", name: "Footer with Globe", slug: "footer-with-globe", description: "Premium footer with animated SVG globe showing office locations, rotating timezone clocks, and CTA strip.", price: 139, teamPrice: 259, enterprisePrice: 459, category: categories[10], categoryId: "c11", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/globe-footer.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1650, averageRating: 4.8, reviewCount: 62, creator: users[3], creatorId: "u4", createdAt: "2024-10-18", updatedAt: "2024-12-14" },

    { id: "comp47", name: "Virtual Scroll Table", slug: "virtual-scroll-table", description: "Lightning-fast table with virtual scrolling for 100K+ rows, frozen columns, inline editing, and exports.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[11], categoryId: "c12", tags: makeTags([0, 2, 3, 7, 9]), images: ["/placeholder.svg"], fileUrl: "/files/virtual-table.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2130, averageRating: 4.9, reviewCount: 85, creator: users[1], creatorId: "u2", createdAt: "2024-09-05", updatedAt: "2024-12-12" },
    { id: "comp48", name: "Expandable Row Table", slug: "expandable-row-table", description: "Data table with expandable detail rows, nested subtables, batch action toolbar, and column visibility toggle.", price: 189, teamPrice: 339, enterprisePrice: 539, category: categories[11], categoryId: "c12", tags: makeTags([0, 1, 3, 7, 9]), images: ["/placeholder.svg"], fileUrl: "/files/expand-table.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1890, averageRating: 4.7, reviewCount: 73, creator: users[0], creatorId: "u1", createdAt: "2024-08-22", updatedAt: "2024-11-25" },

    { id: "comp49", name: "Funnel Analytics Chart", slug: "funnel-analytics-chart", description: "Conversion funnel chart with animated fill, drop-off percentages, hover tooltips, and comparison mode.", price: 179, teamPrice: 329, enterprisePrice: 529, category: categories[12], categoryId: "c13", tags: makeTags([0, 2, 3, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/funnel-chart.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1450, averageRating: 4.7, reviewCount: 55, creator: users[2], creatorId: "u3", createdAt: "2024-10-08", updatedAt: "2024-12-05" },
    { id: "comp50", name: "Real-Time Live Chart", slug: "real-time-live-chart", description: "Streaming data chart with WebSocket support, configurable refresh rate, and auto-scroll with pause-on-hover.", price: 219, teamPrice: 369, enterprisePrice: 569, category: categories[12], categoryId: "c13", tags: makeTags([0, 1, 2, 3, 9]), images: ["/placeholder.svg"], fileUrl: "/files/live-chart.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2670, averageRating: 4.9, reviewCount: 104, creator: users[1], creatorId: "u2", createdAt: "2024-06-25", updatedAt: "2024-12-14" },
    { id: "comp51", name: "Geo Heatmap Chart", slug: "geo-heatmap-chart", description: "World/country heatmap built on D3.js with animated zoom, region click events, and gradient legend.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[12], categoryId: "c13", tags: makeTags([0, 2, 3, 4, 9]), images: ["/placeholder.svg"], fileUrl: "/files/geo-heatmap.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1340, averageRating: 4.8, reviewCount: 50, creator: users[4], creatorId: "u5", createdAt: "2024-11-01", updatedAt: "2024-12-10" },

    { id: "comp52", name: "Product Detail Page", slug: "product-detail-page", description: "Full e-commerce product detail page with image gallery zoom, variant selector, review stars, and sticky buy bar.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[13], categoryId: "c14", tags: makeTags([0, 1, 3, 5, 9]), images: ["/placeholder.svg"], fileUrl: "/files/product-detail.zip", version: "2.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3780, averageRating: 4.8, reviewCount: 147, creator: users[2], creatorId: "u3", createdAt: "2024-05-18", updatedAt: "2024-12-15" },
    { id: "comp53", name: "Shopping Cart Drawer", slug: "shopping-cart-drawer", description: "Slide-out cart drawer with quantity controls, upsell suggestions, promo code input, and Express Checkout buttons.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[13], categoryId: "c14", tags: makeTags([0, 1, 3, 4, 5]), images: ["/placeholder.svg"], fileUrl: "/files/cart-drawer.zip", version: "1.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2980, averageRating: 4.7, reviewCount: 116, creator: users[0], creatorId: "u1", createdAt: "2024-06-30", updatedAt: "2024-12-08" },
    { id: "comp54", name: "Wishlist Page", slug: "wishlist-page", description: "Stunning wishlist page with move-to-cart, share list, price drop alerts, and availability badges.", price: 149, teamPrice: 279, enterprisePrice: 479, category: categories[13], categoryId: "c14", tags: makeTags([0, 1, 3, 5, 7]), images: ["/placeholder.svg"], fileUrl: "/files/wishlist-page.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1540, averageRating: 4.6, reviewCount: 58, creator: users[3], creatorId: "u4", createdAt: "2024-09-14", updatedAt: "2024-11-22" },

    { id: "comp55", name: "MDX Blog Engine", slug: "mdx-blog-engine", description: "Full-featured MDX blog engine with frontmatter, category pages, RSS feed, and reading time estimator.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[14], categoryId: "c15", tags: makeTags([0, 1, 2, 3, 9]), images: ["/placeholder.svg"], fileUrl: "/files/mdx-blog.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2430, averageRating: 4.8, reviewCount: 94, creator: users[1], creatorId: "u2", createdAt: "2024-04-28", updatedAt: "2024-12-12" },
    { id: "comp56", name: "Newsletter Blog Template", slug: "newsletter-blog-template", description: "Substack-inspired newsletter template with subscriber count, issue archive, preview cards, and email CTA.", price: 169, teamPrice: 309, enterprisePrice: 509, category: categories[14], categoryId: "c15", tags: makeTags([0, 1, 3, 5, 6]), images: ["/placeholder.svg"], fileUrl: "/files/newsletter-blog.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1760, averageRating: 4.7, reviewCount: 66, creator: users[4], creatorId: "u5", createdAt: "2024-08-28", updatedAt: "2024-11-28" },

    { id: "comp57", name: "Liquid Button Pack", slug: "liquid-button-pack", description: "12 premium animated buttons with liquid fill, ripple, magnetic hover, and glitch effects.", price: 99, teamPrice: 189, enterprisePrice: 389, category: categories[15], categoryId: "c16", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/liquid-buttons.zip", version: "1.4.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 5340, averageRating: 4.9, reviewCount: 214, creator: users[0], creatorId: "u1", createdAt: "2024-03-10", updatedAt: "2024-12-10" },
    { id: "comp58", name: "Number Ticker", slug: "number-ticker", description: "Animated number counter with slot-machine rolling digits, easing curves, currency formatting, and on-scroll trigger.", price: 79, teamPrice: 149, enterprisePrice: 299, category: categories[15], categoryId: "c16", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/number-ticker.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 4120, averageRating: 4.8, reviewCount: 167, creator: users[2], creatorId: "u3", createdAt: "2024-05-05", updatedAt: "2024-11-18" },
    { id: "comp59", name: "Magnetic Cursor Trail", slug: "magnetic-cursor-trail", description: "Custom cursor with configurable trails, magnetic pull on links/buttons, and scroll velocity effects.", price: 119, teamPrice: 229, enterprisePrice: 429, category: categories[15], categoryId: "c16", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/cursor-trail.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3980, averageRating: 4.9, reviewCount: 158, creator: users[3], creatorId: "u4", createdAt: "2024-05-30", updatedAt: "2024-12-05" },
    { id: "comp60", name: "Infinite Logo Marquee", slug: "infinite-logo-marquee", description: "Seamless infinite scrolling logo marquee with pause on hover, gradient fades, and configurable speed.", price: 59, teamPrice: 119, enterprisePrice: 249, category: categories[15], categoryId: "c16", tags: makeTags([0, 3, 4, 5, 8]), images: ["/placeholder.svg"], fileUrl: "/files/logo-marquee.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 4560, averageRating: 4.8, reviewCount: 182, creator: users[1], creatorId: "u2", createdAt: "2024-04-05", updatedAt: "2024-11-10" },

    { id: "comp61", name: "3D Planet Scene", slug: "3d-planet-scene", description: "Interactive Three.js planet with atmospheric glow, orbit controls, cloud layer, and city lights on dark side.", price: 279, teamPrice: 429, enterprisePrice: 629, category: categories[16], categoryId: "c17", tags: makeTags([0, 3, 4, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/planet-scene.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1820, averageRating: 4.9, reviewCount: 71, creator: users[4], creatorId: "u5", createdAt: "2024-06-08", updatedAt: "2024-12-12" },
    { id: "comp62", name: "3D Product Viewer", slug: "3d-product-viewer", description: "360° product viewer with Three.js, GLTF model loading, environment mapping, and annotation hotspots.", price: 319, teamPrice: 469, enterprisePrice: 669, category: categories[16], categoryId: "c17", tags: makeTags([0, 1, 3, 4, 9]), images: ["/placeholder.svg"], fileUrl: "/files/3d-product.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1430, averageRating: 4.8, reviewCount: 55, creator: users[0], creatorId: "u1", createdAt: "2024-07-18", updatedAt: "2024-12-08" },
    { id: "comp63", name: "WebGL Fluid Simulation", slug: "webgl-fluid-simulation", description: "GPU-accelerated fluid dynamics simulation reacting to mouse/touch, embeddable as an interactive background.", price: 349, teamPrice: 499, enterprisePrice: 699, category: categories[16], categoryId: "c17", tags: makeTags([0, 4, 8, 9, 2]), images: ["/placeholder.svg"], fileUrl: "/files/fluid-sim.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2260, averageRating: 5.0, reviewCount: 88, creator: users[2], creatorId: "u3", createdAt: "2024-05-15", updatedAt: "2024-12-15" },

    // ── extra variety ────────────────────────────────────────────────────────
    { id: "comp64", name: "Toast Notification System", slug: "toast-notification-system", description: "Configurable toast system with progress bars, action buttons, multi-stack, and queue management.", price: 89, teamPrice: 179, enterprisePrice: 379, category: categories[5], categoryId: "c6", tags: makeTags([0, 1, 3, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/toast-system.zip", version: "2.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 4870, averageRating: 4.9, reviewCount: 196, creator: users[3], creatorId: "u4", createdAt: "2024-04-12", updatedAt: "2024-12-10" },
    { id: "comp65", name: "Gradient Text Animator", slug: "gradient-text-animator", description: "Library of 20+ animated gradient text effects: aurora, neon, fire, ocean, and custom color stops.", price: 79, teamPrice: 149, enterprisePrice: 299, category: categories[15], categoryId: "c16", tags: makeTags([0, 3, 4, 8, 5]), images: ["/placeholder.svg"], fileUrl: "/files/gradient-text.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3780, averageRating: 4.8, reviewCount: 152, creator: users[1], creatorId: "u2", createdAt: "2024-04-22", updatedAt: "2024-11-28" },
    { id: "comp66", name: "Metrics Sparkline Cards", slug: "metrics-sparkline-cards", description: "KPI cards with embedded inline sparkline charts, delta indicators, and animated trend arrows.", price: 129, teamPrice: 249, enterprisePrice: 449, category: categories[2], categoryId: "c3", tags: makeTags([0, 2, 3, 4, 8]), images: ["/placeholder.svg"], fileUrl: "/files/sparkline-cards.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2560, averageRating: 4.7, reviewCount: 98, creator: users[4], creatorId: "u5", createdAt: "2024-08-08", updatedAt: "2024-12-05" },
    { id: "comp67", name: "Date Range Picker", slug: "date-range-picker", description: "Headless date range picker with dual-month view, preset ranges (7d/30d/90d), and accessible keyboard navigation.", price: 119, teamPrice: 229, enterprisePrice: 429, category: categories[3], categoryId: "c4", tags: makeTags([0, 2, 3, 7, 9]), images: ["/placeholder.svg"], fileUrl: "/files/date-range.zip", version: "1.4.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3450, averageRating: 4.8, reviewCount: 138, creator: users[0], creatorId: "u1", createdAt: "2024-06-15", updatedAt: "2024-12-01" },
    { id: "comp68", name: "Tabbed Content Switcher", slug: "tabbed-content-switcher", description: "Accessible tab component with sliding indicator, keyboard controls, lazy content loading, and icon support.", price: 79, teamPrice: 149, enterprisePrice: 299, category: categories[3], categoryId: "c4", tags: makeTags([0, 3, 5, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/tabs.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3210, averageRating: 4.7, reviewCount: 127, creator: users[2], creatorId: "u3", createdAt: "2024-07-05", updatedAt: "2024-11-22" },
    { id: "comp69", name: "Stepper Progress Indicator", slug: "stepper-progress-indicator", description: "Multi-step progress indicator with vertical and horizontal variants, optional descriptions, and icon nodes.", price: 79, teamPrice: 149, enterprisePrice: 299, category: categories[3], categoryId: "c4", tags: makeTags([0, 3, 5, 7, 8]), images: ["/placeholder.svg"], fileUrl: "/files/stepper.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2780, averageRating: 4.8, reviewCount: 109, creator: users[1], creatorId: "u2", createdAt: "2024-09-08", updatedAt: "2024-12-03" },

    { id: "comp70", name: "Color Palette Generator", slug: "color-palette-generator", description: "Interactive tool component for generating harmonious color palettes from a seed color with WCAG contrast checking.", price: 149, teamPrice: 279, enterprisePrice: 479, category: categories[15], categoryId: "c16", tags: makeTags([0, 1, 2, 3, 8]), images: ["/placeholder.svg"], fileUrl: "/files/color-gen.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1870, averageRating: 4.7, reviewCount: 72, creator: users[3], creatorId: "u4", createdAt: "2024-10-25", updatedAt: "2024-12-05" },

    // ── 🎮 MORE 3D COMPONENTS (Three.js / WebGL) ─────────────────────────────
    { id: "comp71", name: "Interactive Galaxy Scene", slug: "interactive-galaxy-scene", description: "Stunning Three.js galaxy with 50,000 procedural stars, mouse-parallax camera, animated nebula clouds, and audio-reactive pulsing.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[16], categoryId: "c17", tags: makeTags([0, 10, 12, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/galaxy.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2180, averageRating: 5.0, reviewCount: 87, creator: users[1], creatorId: "u2", createdAt: "2024-05-22", updatedAt: "2024-12-14" },
    { id: "comp72", name: "3D Data Globe", slug: "3d-data-globe", description: "WebGL globe with animated arc connections between countries, click-to-drill-down, and real-time data overlays. Perfect for analytics dashboards.", price: 329, teamPrice: 479, enterprisePrice: 679, category: categories[16], categoryId: "c17", tags: makeTags([0, 1, 10, 12, 9]), images: ["/placeholder.svg"], fileUrl: "/files/3d-globe.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1950, averageRating: 4.9, reviewCount: 76, creator: users[0], creatorId: "u1", createdAt: "2024-06-10", updatedAt: "2024-12-12" },
    { id: "comp73", name: "3D Morphing Blob", slug: "3d-morphing-blob", description: "Organic morphing blob background built with Three.js vertex shaders and simplex noise. Responds to scroll and mouse movement.", price: 189, teamPrice: 349, enterprisePrice: 549, category: categories[16], categoryId: "c17", tags: makeTags([0, 10, 12, 8, 2]), images: ["/placeholder.svg"], fileUrl: "/files/blob-3d.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2640, averageRating: 4.8, reviewCount: 103, creator: users[2], creatorId: "u3", createdAt: "2024-07-14", updatedAt: "2024-11-30" },
    { id: "comp74", name: "3D Floating Island", slug: "3d-floating-island", description: "Low-poly 3D island scene with animated waves, day/night cycle, drifting clouds, and orbit controls for demos.", price: 279, teamPrice: 429, enterprisePrice: 629, category: categories[16], categoryId: "c17", tags: makeTags([0, 10, 11, 12, 21]), images: ["/placeholder.svg"], fileUrl: "/files/floating-island.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1420, averageRating: 4.8, reviewCount: 55, creator: users[4], creatorId: "u5", createdAt: "2024-09-20", updatedAt: "2024-12-02" },

    // ── 🤖 SPLINE 3D MODELS (embed-ready scenes) ─────────────────────────────
    { id: "comp75", name: "Interactive Robot Hero Scene", slug: "interactive-robot-hero", description: "The iconic robot hero scene from our homepage — a fully interactive Spline 3D robot you can drag, rotate, and animate. Includes hover glow, idle breathing animation, and spotlight. Drop-in embed using @splinetool/react-spline.", longDescription: "This is the exact same interactive robot you see on our hero page. Built in Spline and exported as a React-embeddable scene. The robot breathes when idle, reacts to mouse hover with a glow pulse, and can be freely rotated by dragging. Includes full Next.js integration code, loading skeleton, and optional camera controls.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[17], categoryId: "c18", tags: makeTags([0, 1, 11, 12, 21]), images: ["/placeholder.svg"], fileUrl: "/files/robot-hero.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4870, averageRating: 5.0, reviewCount: 194, creator: users[0], creatorId: "u1", createdAt: "2024-04-01", updatedAt: "2024-12-15" },
    { id: "comp76", name: "3D Product Showcase Scene", slug: "3d-product-showcase-spline", description: "Spline scene with a floating product box on a reflective surface, customisable color, orbiting highlight lights, and explode animation on click.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[17], categoryId: "c18", tags: makeTags([0, 11, 12, 21, 21]), images: ["/placeholder.svg"], fileUrl: "/files/spline-product.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2340, averageRating: 4.9, reviewCount: 92, creator: users[1], creatorId: "u2", createdAt: "2024-05-15", updatedAt: "2024-12-10" },
    { id: "comp77", name: "3D Astronaut Scene", slug: "3d-astronaut-scene", description: "Floating astronaut in deep space Spline scene with waving hand animation, star particle background, and mouse-reactive drift. Perfect for 404 pages and hero sections.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[17], categoryId: "c18", tags: makeTags([0, 11, 12, 8, 21]), images: ["/placeholder.svg"], fileUrl: "/files/spline-astronaut.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3120, averageRating: 4.9, reviewCount: 128, creator: users[3], creatorId: "u4", createdAt: "2024-06-01", updatedAt: "2024-12-08" },
    { id: "comp78", name: "3D Crystal Ball", slug: "3d-crystal-ball", description: "Magical crystal sphere Spline scene with refraction shaders, swirling inner smoke, and glow bloom on hover. Great for creative landing pages.", price: 179, teamPrice: 329, enterprisePrice: 529, category: categories[17], categoryId: "c18", tags: makeTags([0, 11, 12, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/spline-crystal.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1870, averageRating: 4.8, reviewCount: 73, creator: users[2], creatorId: "u3", createdAt: "2024-07-10", updatedAt: "2024-11-28" },
    { id: "comp79", name: "3D DNA Helix Loader", slug: "3d-dna-helix-loader", description: "Animated Spline DNA double-helix used as a premium loading skeleton or hero visual. Color-customizable via CSS variables.", price: 149, teamPrice: 279, enterprisePrice: 479, category: categories[17], categoryId: "c18", tags: makeTags([0, 11, 12, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/spline-dna.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1540, averageRating: 4.7, reviewCount: 61, creator: users[4], creatorId: "u5", createdAt: "2024-08-18", updatedAt: "2024-12-01" },
    { id: "comp80", name: "3D Macbook Mockup", slug: "3d-macbook-mockup", description: "Photorealistic Spline Macbook that opens on scroll, shows your website on the screen, and supports live iframe injection.", price: 269, teamPrice: 419, enterprisePrice: 619, category: categories[17], categoryId: "c18", tags: makeTags([0, 1, 11, 12, 21]), images: ["/placeholder.svg"], fileUrl: "/files/spline-macbook.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2890, averageRating: 4.9, reviewCount: 114, creator: users[0], creatorId: "u1", createdAt: "2024-05-08", updatedAt: "2024-12-14" },
    { id: "comp81", name: "3D Floating Cards Stack", slug: "3d-floating-cards-spline", description: "A stack of glassmorphic cards in Spline, each hovering at different heights, with a cascade scatter animation on click.", price: 159, teamPrice: 299, enterprisePrice: 499, category: categories[17], categoryId: "c18", tags: makeTags([0, 11, 12, 8, 9]), images: ["/placeholder.svg"], fileUrl: "/files/spline-cards.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1650, averageRating: 4.7, reviewCount: 64, creator: users[2], creatorId: "u3", createdAt: "2024-09-12", updatedAt: "2024-11-22" },
    { id: "comp82", name: "3D AI Brain Visualization", slug: "3d-ai-brain", description: "Neural network brain mesh in Spline with animated synapse pulses, node activation effects, and zoom-on-hover for AI/ML product pages.", price: 319, teamPrice: 469, enterprisePrice: 669, category: categories[17], categoryId: "c18", tags: makeTags([0, 1, 11, 12, 21]), images: ["/placeholder.svg"], fileUrl: "/files/spline-brain.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2210, averageRating: 4.9, reviewCount: 88, creator: users[1], creatorId: "u2", createdAt: "2024-06-28", updatedAt: "2024-12-12" },
    { id: "comp83", name: "3D Phone Mockup Scene", slug: "3d-phone-mockup-spline", description: "Spinning iPhone-style Spline phone with your app on screen, auto-rotate demo mode, and tap-to-interact annotation bubbles.", price: 229, teamPrice: 379, enterprisePrice: 579, category: categories[17], categoryId: "c18", tags: makeTags([0, 11, 12, 5, 21]), images: ["/placeholder.svg"], fileUrl: "/files/spline-phone.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2480, averageRating: 4.8, reviewCount: 97, creator: users[3], creatorId: "u4", createdAt: "2024-07-22", updatedAt: "2024-12-05" },

    // ── ⚡ APIs & INTEGRATIONS ─────────────────────────────────────────────────
    { id: "comp84", name: "Stripe Payment SDK Kit", slug: "stripe-payment-sdk", description: "Complete Stripe integration: payment intents, subscriptions, webhooks handler, and a beautiful checkout UI. One-time setup, production-ready.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 13, 14, 20]), images: ["/placeholder.svg"], fileUrl: "/files/stripe-sdk.zip", version: "3.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 5640, averageRating: 4.9, reviewCount: 231, creator: users[0], creatorId: "u1", createdAt: "2024-03-01", updatedAt: "2024-12-15" },
    { id: "comp85", name: "OpenAI GPT API Wrapper", slug: "openai-gpt-wrapper", description: "Type-safe OpenAI wrapper with streaming support, token counting, error retry, rate-limit backoff, and a plug-and-play chat UI.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 13, 20]), images: ["/placeholder.svg"], fileUrl: "/files/openai-wrapper.zip", version: "2.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 7230, averageRating: 5.0, reviewCount: 289, creator: users[1], creatorId: "u2", createdAt: "2024-02-15", updatedAt: "2024-12-14" },
    { id: "comp86", name: "SendGrid Email API Kit", slug: "sendgrid-email-api", description: "SendGrid integration with transactional email, template engine, bounce handling, unsubscribe groups, and email analytics dashboard.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 13, 14, 20]), images: ["/placeholder.svg"], fileUrl: "/files/sendgrid-kit.zip", version: "1.4.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3870, averageRating: 4.8, reviewCount: 154, creator: users[2], creatorId: "u3", createdAt: "2024-04-10", updatedAt: "2024-12-08" },
    { id: "comp87", name: "Google Maps Integration", slug: "google-maps-api", description: "Fully-featured Google Maps React component with custom styled maps, marker clustering, directions, places autocomplete, and heatmap overlay.", price: 229, teamPrice: 379, enterprisePrice: 579, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 13, 5]), images: ["/placeholder.svg"], fileUrl: "/files/gmaps-kit.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4120, averageRating: 4.8, reviewCount: 168, creator: users[3], creatorId: "u4", createdAt: "2024-04-25", updatedAt: "2024-12-12" },
    { id: "comp88", name: "Firebase Auth & DB Kit", slug: "firebase-auth-db", description: "Complete Firebase v10 integration: email/social auth, Firestore CRUD hooks, real-time listener utilities, and security rules templates.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 13, 20]), images: ["/placeholder.svg"], fileUrl: "/files/firebase-kit.zip", version: "2.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 4560, averageRating: 4.8, reviewCount: 184, creator: users[4], creatorId: "u5", createdAt: "2024-03-20", updatedAt: "2024-12-10" },
    { id: "comp89", name: "Twilio SMS & Voice API", slug: "twilio-sms-voice", description: "Twilio SDK wrapper for OTP SMS, in-app voice calls, WhatsApp messaging, and conversation tracking — with a built-in webhook server.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[18], categoryId: "c19", tags: makeTags([0, 13, 14, 15, 20]), images: ["/placeholder.svg"], fileUrl: "/files/twilio-kit.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2870, averageRating: 4.7, reviewCount: 112, creator: users[0], creatorId: "u1", createdAt: "2024-05-18", updatedAt: "2024-11-30" },
    { id: "comp90", name: "GitHub API Dashboard", slug: "github-api-dashboard", description: "GitHub API integration with repo stats, commit graphs, PR review board, issue tracker, and contributor leaderboards — all in one dashboard.", price: 279, teamPrice: 429, enterprisePrice: 629, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 13, 14]), images: ["/placeholder.svg"], fileUrl: "/files/github-dashboard.zip", version: "1.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3450, averageRating: 4.9, reviewCount: 138, creator: users[1], creatorId: "u2", createdAt: "2024-05-05", updatedAt: "2024-12-14" },
    { id: "comp91", name: "Cloudinary Image API Kit", slug: "cloudinary-image-api", description: "Cloudinary integration with upload widget, transformation pipeline, lazy-loading CDN images, and automatic WebP conversion.", price: 169, teamPrice: 309, enterprisePrice: 509, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 13, 14, 5]), images: ["/placeholder.svg"], fileUrl: "/files/cloudinary-kit.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2780, averageRating: 4.7, reviewCount: 109, creator: users[2], creatorId: "u3", createdAt: "2024-06-18", updatedAt: "2024-12-05" },
    { id: "comp92", name: "Webhook Dashboard Builder", slug: "webhook-dashboard", description: "Generic webhook ingestion dashboard — receives, logs, replays, and visualizes webhook events from any provider with signature verification.", price: 219, teamPrice: 369, enterprisePrice: 569, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 15, 20]), images: ["/placeholder.svg"], fileUrl: "/files/webhook-dash.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1890, averageRating: 4.8, reviewCount: 75, creator: users[3], creatorId: "u4", createdAt: "2024-08-01", updatedAt: "2024-12-08" },
    { id: "comp93", name: "Resend Email API UI Kit", slug: "resend-email-kit", description: "Resend.com integration with React Email templates, preview server, attachment support, and delivery analytics dashboard.", price: 179, teamPrice: 329, enterprisePrice: 529, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 13, 20]), images: ["/placeholder.svg"], fileUrl: "/files/resend-kit.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 3120, averageRating: 4.9, reviewCount: 125, creator: users[0], creatorId: "u1", createdAt: "2024-07-08", updatedAt: "2024-12-12" },
    { id: "comp94", name: "REST API Playground UI", slug: "rest-api-playground", description: "In-browser API explorer like Postman — send requests, test endpoints, view responses, manage collections, and auto-generate code snippets.", price: 319, teamPrice: 469, enterprisePrice: 669, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 2, 13, 7]), images: ["/placeholder.svg"], fileUrl: "/files/api-playground.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4230, averageRating: 4.9, reviewCount: 170, creator: users[1], creatorId: "u2", createdAt: "2024-04-18", updatedAt: "2024-12-15" },
    { id: "comp95", name: "S3 File Manager UI", slug: "s3-file-manager", description: "AWS S3 / R2 / MinIO file manager component with folder tree, drag-and-drop upload, signed URL downloads, and bulk operations.", price: 259, teamPrice: 409, enterprisePrice: 609, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 13, 20, 5]), images: ["/placeholder.svg"], fileUrl: "/files/s3-manager.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2340, averageRating: 4.8, reviewCount: 93, creator: users[2], creatorId: "u3", createdAt: "2024-08-22", updatedAt: "2024-12-08" },
    { id: "comp96", name: "Paddle Billing Integration", slug: "paddle-billing", description: "Paddle subscription billing UI with trial management, upgrade/downgrade flows, proration display, and cancellation surveys.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[18], categoryId: "c19", tags: makeTags([0, 1, 13, 14, 15]), images: ["/placeholder.svg"], fileUrl: "/files/paddle-kit.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1450, averageRating: 4.7, reviewCount: 57, creator: users[4], creatorId: "u5", createdAt: "2024-09-15", updatedAt: "2024-12-01" },

    // ── 🛡️ SECURITY & ANTIVIRUS ───────────────────────────────────────────────
    { id: "comp97", name: "Real-Time Malware Scanner UI", slug: "malware-scanner-ui", description: "Antivirus scanning dashboard with animated scan progress, threat severity badges, quarantine list, and scan history timeline.", price: 349, teamPrice: 499, enterprisePrice: 699, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 2, 16, 17]), images: ["/placeholder.svg"], fileUrl: "/files/malware-scanner.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 1870, averageRating: 4.9, reviewCount: 74, creator: users[0], creatorId: "u1", createdAt: "2024-06-12", updatedAt: "2024-12-14" },
    { id: "comp98", name: "Security Threat Dashboard", slug: "security-threat-dashboard", description: "Live cybersecurity dashboard with geo threat map, attack-type charts, CVE feed, firewall event log, and severity heatmap.", price: 399, teamPrice: 549, enterprisePrice: 749, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 2, 16, 17]), images: ["/placeholder.svg"], fileUrl: "/files/threat-dashboard.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 2340, averageRating: 5.0, reviewCount: 93, creator: users[1], creatorId: "u2", createdAt: "2024-05-20", updatedAt: "2024-12-15" },
    { id: "comp99", name: "Password Vault UI Component", slug: "password-vault-ui", description: "End-to-end encrypted password manager UI with AES-256 encryption, password strength meter, breach check, and category organizer.", price: 279, teamPrice: 429, enterprisePrice: 629, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 2, 16, 7]), images: ["/placeholder.svg"], fileUrl: "/files/password-vault.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1560, averageRating: 4.8, reviewCount: 62, creator: users[2], creatorId: "u3", createdAt: "2024-07-18", updatedAt: "2024-12-08" },
    { id: "comp100", name: "Security Access Gate UI", slug: "security-access-gate", description: "Security gate component enforcing 2FA + device fingerprint + IP change alerts before granting access to protected routes.", price: 229, teamPrice: 379, enterprisePrice: 579, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 16, 17, 7]), images: ["/placeholder.svg"], fileUrl: "/files/security-gate.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1980, averageRating: 4.8, reviewCount: 79, creator: users[3], creatorId: "u4", createdAt: "2024-08-05", updatedAt: "2024-11-28" },
    { id: "comp101", name: "SSL Certificate Monitor", slug: "ssl-cert-monitor", description: "SSL/TLS certificate monitoring UI with expiry countdown, chain validation, HSTS check, and Slack/email alert integration.", price: 189, teamPrice: 339, enterprisePrice: 539, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 13, 16, 20]), images: ["/placeholder.svg"], fileUrl: "/files/ssl-monitor.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1340, averageRating: 4.7, reviewCount: 53, creator: users[4], creatorId: "u5", createdAt: "2024-09-08", updatedAt: "2024-12-02" },
    { id: "comp102", name: "GDPR Consent Manager UI", slug: "gdpr-consent-manager", description: "Beautiful GDPR consent banner and preferences panel with category toggles, consent log, region detection, and Google Consent Mode v2 support.", price: 219, teamPrice: 369, enterprisePrice: 569, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 2, 16, 5]), images: ["/placeholder.svg"], fileUrl: "/files/gdpr-consent.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4120, averageRating: 4.9, reviewCount: 165, creator: users[0], creatorId: "u1", createdAt: "2024-04-05", updatedAt: "2024-12-12" },
    { id: "comp103", name: "Security Audit Report Generator", slug: "security-audit-report", description: "Renders a printable/PDF security audit report from JSON scan data — with risk score, findings table, and remediation checklist.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[19], categoryId: "c20", tags: makeTags([0, 2, 16, 17, 20]), images: ["/placeholder.svg"], fileUrl: "/files/audit-report.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 980, averageRating: 4.8, reviewCount: 39, creator: users[1], creatorId: "u2", createdAt: "2024-10-12", updatedAt: "2024-12-10" },
    { id: "comp104", name: "Firewall Rules Manager UI", slug: "firewall-rules-manager", description: "Network firewall rule CRUD interface with drag priority sorting, IP range validation, protocol filters, and rule conflict detection.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[19], categoryId: "c20", tags: makeTags([0, 1, 2, 16, 7]), images: ["/placeholder.svg"], fileUrl: "/files/firewall-ui.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 870, averageRating: 4.7, reviewCount: 34, creator: users[2], creatorId: "u3", createdAt: "2024-11-05", updatedAt: "2024-12-14" },

    // ── 🖨️ PRINTERS & HARDWARE INTEGRATIONS ──────────────────────────────────
    { id: "comp105", name: "Thermal Receipt Printer SDK", slug: "thermal-receipt-printer", description: "Browser-to-thermal-printer bridge using ESC/POS protocol. Print receipts, tickets, and invoices directly from your web app via USB/Bluetooth/Network.", price: 299, teamPrice: 449, enterprisePrice: 649, category: categories[20], categoryId: "c21", tags: makeTags([0, 1, 18, 19, 20]), images: ["/placeholder.svg"], fileUrl: "/files/thermal-printer-sdk.zip", version: "2.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 3120, averageRating: 4.9, reviewCount: 124, creator: users[3], creatorId: "u4", createdAt: "2024-04-15", updatedAt: "2024-12-14" },
    { id: "comp106", name: "Invoice PDF Printer UI", slug: "invoice-pdf-printer", description: "Professional invoice designer with live preview, auto-numbering, tax calculation, multi-currency, and one-click PDF/print output.", price: 249, teamPrice: 399, enterprisePrice: 599, category: categories[20], categoryId: "c21", tags: makeTags([0, 1, 2, 19, 20]), images: ["/placeholder.svg"], fileUrl: "/files/invoice-printer.zip", version: "1.5.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 4780, averageRating: 4.9, reviewCount: 192, creator: users[4], creatorId: "u5", createdAt: "2024-03-22", updatedAt: "2024-12-15" },
    { id: "comp107", name: "Label Printer Integration", slug: "label-printer-sdk", description: "Zebra and DYMO label printer SDK for React. Design labels visually, set print quantity, preview before print, and manage printer queue.", price: 279, teamPrice: 429, enterprisePrice: 629, category: categories[20], categoryId: "c21", tags: makeTags([0, 1, 14, 19, 20]), images: ["/placeholder.svg"], fileUrl: "/files/label-printer.zip", version: "1.2.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 1870, averageRating: 4.8, reviewCount: 75, creator: users[0], creatorId: "u1", createdAt: "2024-06-08", updatedAt: "2024-12-10" },
    { id: "comp108", name: "Barcode & QR Scanner UI", slug: "barcode-qr-scanner", description: "Camera-based barcode and QR code scanner with multi-format support, batch scan mode, history list, and product lookup API hooks.", price: 199, teamPrice: 349, enterprisePrice: 549, category: categories[20], categoryId: "c21", tags: makeTags([0, 1, 13, 19, 5]), images: ["/placeholder.svg"], fileUrl: "/files/barcode-scanner.zip", version: "1.3.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: true, downloadCount: 5340, averageRating: 4.9, reviewCount: 214, creator: users[1], creatorId: "u2", createdAt: "2024-04-20", updatedAt: "2024-12-12" },
    { id: "comp109", name: "Print Queue Manager Dashboard", slug: "print-queue-dashboard", description: "Admin dashboard to monitor multiple printers, manage print queues, view ink/toner levels, and receive alerts for paper jams or offline printers.", price: 329, teamPrice: 479, enterprisePrice: 679, category: categories[20], categoryId: "c21", tags: makeTags([0, 1, 2, 19, 20]), images: ["/placeholder.svg"], fileUrl: "/files/print-queue-dash.zip", version: "1.0.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 980, averageRating: 4.7, reviewCount: 39, creator: users[2], creatorId: "u3", createdAt: "2024-09-28", updatedAt: "2024-12-08" },
    { id: "comp110", name: "POS Receipt Template Builder", slug: "pos-receipt-builder", description: "Point-of-sale receipt template designer — drag-and-drop layout, logo upload, configurable line items, footer messages, and barcode insertion.", price: 219, teamPrice: 369, enterprisePrice: 569, category: categories[20], categoryId: "c21", tags: makeTags([0, 1, 19, 20, 5]), images: ["/placeholder.svg"], fileUrl: "/files/pos-receipt.zip", version: "1.1.0", framework: "nextjs", styling: "tailwindcss", status: "PUBLISHED", featured: false, downloadCount: 2340, averageRating: 4.8, reviewCount: 93, creator: users[3], creatorId: "u4", createdAt: "2024-07-14", updatedAt: "2024-12-05" },
];

export const reviews: Review[] = [
    { id: "r1", rating: 5, title: "Absolutely stunning!", comment: "The Aurora Hero Section completely transformed my landing page. The animations are buttery smooth and the code is well-structured.", verified: true, helpful: 42, user: users[5], userId: "u6", componentId: "comp1", createdAt: "2024-09-15" },
    { id: "r2", rating: 5, title: "Best navbar I've used", comment: "Glass effect is gorgeous. Works perfectly on all devices. Easy to customize.", verified: true, helpful: 38, user: users[6], userId: "u7", componentId: "comp2", createdAt: "2024-08-20" },
    { id: "r3", rating: 4, title: "Great dashboard kit", comment: "Very comprehensive. Took a bit to set up but the end result is amazing.", verified: true, helpful: 25, user: users[5], userId: "u6", componentId: "comp3", createdAt: "2024-10-05" },
    { id: "r4", rating: 5, title: "Saved me weeks of work", comment: "The SaaS landing page kit is incredible. Everything is pixel-perfect.", verified: true, helpful: 56, user: users[6], userId: "u7", componentId: "comp8", createdAt: "2024-07-25" },
    { id: "r5", rating: 5, title: "Mind-blowing animations", comment: "The scroll animation kit is a game-changer. My clients are always impressed.", verified: true, helpful: 47, user: users[5], userId: "u6", componentId: "comp16", createdAt: "2024-06-10" },
    { id: "r6", rating: 4, title: "Solid data table", comment: "Handles large datasets well. Would love to see virtual scrolling in next update.", verified: true, helpful: 19, user: users[6], userId: "u7", componentId: "comp12", createdAt: "2024-11-01" },
];

export const testimonials: Testimonial[] = [
    { id: "t1", name: "Michael Foster", role: "CTO", company: "TechFlow Inc.", avatar: `${avatarBase}michael`, comment: "ComponentVault saved our team months of development time. The quality of components is outstanding.", rating: 5 },
    { id: "t2", name: "Amanda Reed", role: "Lead Designer", company: "PixelCraft Studios", avatar: `${avatarBase}amanda`, comment: "Finally, a marketplace where every component feels premium. The attention to detail is incredible.", rating: 5 },
    { id: "t3", name: "Ryan Cooper", role: "Indie Developer", company: "Self-employed", avatar: `${avatarBase}ryan`, comment: "I've earned over $50K selling my components here. The platform is a game-changer for creators.", rating: 5 },
    { id: "t4", name: "Jessica Liu", role: "Engineering Manager", company: "ScaleUp Corp", avatar: `${avatarBase}jessica`, comment: "We standardized our UI across 12 products using components from this marketplace. Worth every penny.", rating: 5 },
];

export const blogPosts: BlogPost[] = [
    { id: "b1", title: "Building Beautiful UIs with Framer Motion", slug: "building-beautiful-uis-framer-motion", excerpt: "Learn how to create stunning animations and micro-interactions using Framer Motion in your React applications.", content: "Full blog content here...", coverImage: "/placeholder.svg", author: users[0], category: "Tutorials", tags: ["React", "Animation", "Framer Motion"], readingTime: "8 min read", publishedAt: "2024-12-10" },
    { id: "b2", title: "The Future of Component Marketplaces", slug: "future-component-marketplaces", excerpt: "How AI and design systems are shaping the next generation of UI component marketplaces.", content: "Full blog content here...", coverImage: "/placeholder.svg", author: users[1], category: "Industry", tags: ["AI", "Design Systems", "Marketplace"], readingTime: "6 min read", publishedAt: "2024-12-05" },
    { id: "b3", title: "Tailwind CSS 4: What's New", slug: "tailwind-css-4-whats-new", excerpt: "A deep dive into the new features and improvements coming in Tailwind CSS version 4.", content: "Full blog content here...", coverImage: "/placeholder.svg", author: users[2], category: "News", tags: ["Tailwind CSS", "CSS", "Web Development"], readingTime: "10 min read", publishedAt: "2024-11-28" },
];

export const coupons: Coupon[] = [
    { id: "cp1", code: "LAUNCH20", discountPercent: 20, maxUses: 1000, usedCount: 342, expiresAt: "2025-06-30", active: true },
    { id: "cp2", code: "WELCOME10", discountPercent: 10, maxUses: undefined, usedCount: 1567, active: true },
    { id: "cp3", code: "BUNDLE30", discountPercent: 30, maxUses: 500, usedCount: 123, expiresAt: "2025-03-31", active: true },
    { id: "cp4", code: "HSR101", discountPercent: 100, maxUses: undefined, usedCount: 0, active: true },
    { id: "cp5", code: "HSR199", discountPercent: 0, discountAmount: 248.99, maxUses: undefined, usedCount: 0, active: true },
];

export const samplePurchases: Purchase[] = [
    { id: "p1", userId: "u6", component: components[0], componentId: "comp1", licenseType: "PERSONAL", price: 149, stripePaymentId: "pi_mock_1", createdAt: "2024-11-15" },
    { id: "p2", userId: "u6", component: components[7], componentId: "comp8", licenseType: "TEAM", price: 399, stripePaymentId: "pi_mock_2", createdAt: "2024-11-20" },
    { id: "p3", userId: "u7", component: components[1], componentId: "comp2", licenseType: "PERSONAL", price: 99, stripePaymentId: "pi_mock_3", createdAt: "2024-12-01" },
];

export function getComponentBySlug(slug: string): ComponentItem | undefined {
    return components.find(c => c.slug === slug);
}

export function getComponentsByCategory(categorySlug: string): ComponentItem[] {
    return components.filter(c => c.category.slug === categorySlug);
}

export function getFeaturedComponents(): ComponentItem[] {
    return components.filter(c => c.featured);
}

export function searchComponents(query: string): ComponentItem[] {
    const q = query.toLowerCase();
    return components.filter(c =>
        c.name.toLowerCase().includes(q) ||
        c.description.toLowerCase().includes(q) ||
        c.tags.some(t => t.name.toLowerCase().includes(q))
    );
}

export function getReviewsForComponent(componentId: string): Review[] {
    return reviews.filter(r => r.componentId === componentId);
}
